/**
 * Static typed legal content for Terms of Service and Privacy Policy.
 *
 * Structurally complete across all 14 supported languages (docs/CONTRACT.md §1.2).
 * Layered on the existing interface language store.
 */

import type { LanguageCode } from "./constants";

export interface LegalTermsContent {
  title: string;
  updated: string;
  calloutLead: string;
  calloutBold: string;
  calloutTail: string;
  serviceTitle: string;
  serviceDesc: string;
  qualityTitle: string;
  qualityP1Lead: string;
  qualityP1Bold: string;
  qualityP1Tail: string;
  qualityP2: string;
  responsibilitiesTitle: string;
  responsibilitiesItem1: string;
  responsibilitiesItem2Prefix: string;
  responsibilitiesItem2Link: string;
  responsibilitiesItem2Suffix: string;
  responsibilitiesItem3: string;
  accountsTitle: string;
  accountsDesc: string;
  backToRegister: string;
}

export interface LegalPrivacyContent {
  title: string;
  updated: string;
  calloutLead: string;
  calloutBold: string;
  calloutTail: string;
  storedTitle: string;
  storedP1: string;
  storedP2: string;
  accessTitle: string;
  accessItems: [string, string, string];
  thirdPartyTitle: string;
  thirdPartyDesc: string;
  tableHeaders: [string, string, string];
  tableRows: [
    [string, string, string],
    [string, string, { before: string; bold: string; after: string }],
    [string, string, string]
  ];
  deletionTitle: string;
  deletionDesc: string;
  backToRegister: string;
}

export const TERMS_CONTENT: Record<LanguageCode, LegalTermsContent> = {
  "en": {
    "title": "Terms of Service",
    "updated": "Applicable to the coursework MVP release.",
    "calloutLead": "LinguaFlow is a student coursework project. The system is provided ",
    "calloutBold": "as-is, without warranties of any kind",
    "calloutTail": ", and may experience downtime or data loss at any time.",
    "serviceTitle": "What this service does",
    "serviceDesc": "LinguaFlow translates chat messages into the language each recipient has chosen to read, referencing recent messages as context.",
    "qualityTitle": "Translation quality",
    "qualityP1Lead": "Translations are generated by language models and ",
    "qualityP1Bold": "may contain errors",
    "qualityP1Tail": ". When the primary translation route fails, the system switches to a fallback provider, and if translation is still unavailable, delivers the original text — messages are never lost, but may arrive untranslated.",
    "qualityP2": "Every message allows viewing the original text. For important matters, verify against the original rather than relying solely on translations. Do not use LinguaFlow for situations where mistranslation could cause serious consequences.",
    "responsibilitiesTitle": "Your responsibilities",
    "responsibilitiesItem1": "Do not send illegal, harassing, or rights-infringing content.",
    "responsibilitiesItem2Prefix": "Do not send sensitive personal information — see the ",
    "responsibilitiesItem2Link": "Privacy Policy",
    "responsibilitiesItem2Suffix": " to understand where message content travels.",
    "responsibilitiesItem3": "Keep your login credentials secure.",
    "accountsTitle": "Accounts",
    "accountsDesc": "The development team may delete accounts or data during development without prior notice, as this is an educational project, not a production environment.",
    "backToRegister": "← Back to registration"
  },
  "vi": {
    "title": "Điều khoản dịch vụ",
    "updated": "Áp dụng cho bản MVP dùng trong học phần.",
    "calloutLead": "LinguaFlow là sản phẩm của một bài tập môn học, do nhóm sinh viên phát triển. Hệ thống được cung cấp ",
    "calloutBold": "nguyên trạng, không kèm bảo đảm",
    "calloutTail": ", và có thể ngừng hoạt động hoặc mất dữ liệu bất cứ lúc nào.",
    "serviceTitle": "Dịch vụ này làm gì",
    "serviceDesc": "LinguaFlow dịch tin nhắn trong cuộc trò chuyện sang ngôn ngữ mà mỗi người nhận đã chọn để đọc, có tham chiếu vài tin nhắn gần nhất làm ngữ cảnh.",
    "qualityTitle": "Về chất lượng bản dịch",
    "qualityP1Lead": "Bản dịch do mô hình ngôn ngữ tạo ra và ",
    "qualityP1Bold": "có thể sai",
    "qualityP1Tail": ". Khi đường dịch chính thất bại, hệ thống chuyển sang provider dự phòng, và nếu vẫn không dịch được thì gửi nguyên văn bản gốc — tin nhắn không bao giờ bị mất, nhưng có thể tới người nhận ở dạng chưa dịch.",
    "qualityP2": "Mỗi tin nhắn đều xem lại được bản gốc. Với nội dung quan trọng, hãy đối chiếu bản gốc thay vì chỉ tin vào bản dịch. Không dùng LinguaFlow cho các tình huống mà một câu dịch sai gây hậu quả nghiêm trọng.",
    "responsibilitiesTitle": "Bạn có trách nhiệm",
    "responsibilitiesItem1": "Không gửi nội dung vi phạm pháp luật, quấy rối hoặc xâm phạm quyền của người khác.",
    "responsibilitiesItem2Prefix": "Không gửi thông tin cá nhân nhạy cảm — xem ",
    "responsibilitiesItem2Link": "Chính sách riêng tư",
    "responsibilitiesItem2Suffix": " để biết nội dung tin nhắn đi tới đâu.",
    "responsibilitiesItem3": "Giữ an toàn cho thông tin đăng nhập của mình.",
    "accountsTitle": "Tài khoản",
    "accountsDesc": "Nhóm phát triển có thể xoá tài khoản hoặc dữ liệu trong quá trình phát triển, kể cả không báo trước, vì đây là môi trường học tập chứ không phải môi trường vận hành thật.",
    "backToRegister": "← Quay lại đăng ký"
  },
  "zh": {
    "title": "服务条款",
    "updated": "适用于课程 MVP 版本。",
    "calloutLead": "LinguaFlow 是学生课程作业项目。系统按",
    "calloutBold": "“现状”提供，不作任何保证",
    "calloutTail": "，并可能随时停机或丢失数据。",
    "serviceTitle": "本服务的功能",
    "serviceDesc": "LinguaFlow 将聊天消息翻译为每位接收者选择的阅读语言，并参考最近的消息作为上下文。",
    "qualityTitle": "关于翻译质量",
    "qualityP1Lead": "翻译由语言模型生成，",
    "qualityP1Bold": "可能存在错误",
    "qualityP1Tail": "。当主要翻译通道失败时，系统将切换至备用提供商；若仍无法翻译，则发送原始内容——消息绝不会丢失，但可能以未翻译的形式送达。",
    "qualityP2": "每条消息均可查看原文。对于重要内容，请核对原文而非仅依赖翻译。请勿在翻译错误可能导致严重后果的场合使用 LinguaFlow。",
    "responsibilitiesTitle": "您的责任",
    "responsibilitiesItem1": "不得发送违法、骚扰或侵犯他人权利的内容。",
    "responsibilitiesItem2Prefix": "请勿发送敏感个人信息——请参阅",
    "responsibilitiesItem2Link": "隐私政策",
    "responsibilitiesItem2Suffix": "了解消息内容的去向。",
    "responsibilitiesItem3": "请妥善保管您的登录凭证。",
    "accountsTitle": "账户",
    "accountsDesc": "开发团队可能在开发过程中删除账户或数据（包括未提前通知），因为这是学习环境而非实际运营环境。",
    "backToRegister": "← 返回注册"
  },
  "ja": {
    "title": "利用規約",
    "updated": "授業用 MVP リリースに適用されます。",
    "calloutLead": "LinguaFlow は学生の授業プロジェクトです。本システムは",
    "calloutBold": "いかなる保証もない現状有姿で提供され",
    "calloutTail": "、いつでも停止またはデータ消失が発生する可能性があります。",
    "serviceTitle": "本サービスの概要",
    "serviceDesc": "LinguaFlow は、直近の数件のメッセージを文脈として参照し、各受信者が選択した読解言語にメッセージを翻訳します。",
    "qualityTitle": "翻訳品質について",
    "qualityP1Lead": "翻訳は言語モデルによって生成されるため、",
    "qualityP1Bold": "誤りが含まれる場合があります",
    "qualityP1Tail": "。メインの翻訳経路が失敗した場合はフォールバック先に切り替わり、それでも翻訳できない場合は原文のまま配信されます。メッセージが消失することはありませんが、未翻訳のまま届くことがあります。",
    "qualityP2": "すべてのメッセージで原文を確認できます。重要な内容については翻訳のみに依存せず、必ず原文と照合してください。誤訳が重大な結果を招く可能性がある状況では使用しないでください。",
    "responsibilitiesTitle": "利用者の責任",
    "responsibilitiesItem1": "違法、嫌がらせ、または他者の権利を侵害するコンテンツを送信しないこと。",
    "responsibilitiesItem2Prefix": "機密性の高い個人情報を送信しないこと。メッセージの送信先については",
    "responsibilitiesItem2Link": "プライバシーポリシー",
    "responsibilitiesItem2Suffix": "をご確認ください。",
    "responsibilitiesItem3": "ログイン情報を安全に保管すること。",
    "accountsTitle": "アカウント",
    "accountsDesc": "本システムは学習環境であり実際の商用環境ではないため、開発中に予告なくアカウントやデータが削除されることがあります。",
    "backToRegister": "← 登録に戻る"
  },
  "ko": {
    "title": "서비스 이용약관",
    "updated": "수업용 MVP 릴리스에 적용됩니다.",
    "calloutLead": "LinguaFlow는 학생 수업 프로젝트입니다. 본 시스템은 ",
    "calloutBold": "어떠한 보증도 없이 있는 그대로 제공되며",
    "calloutTail": ", 언제든지 서비스가 중단되거나 데이터가 손실될 수 있습니다.",
    "serviceTitle": "서비스 제공 내용",
    "serviceDesc": "LinguaFlow는 대화의 최근 메시지를 문맥으로 참조하여 각 수신자가 선택한 언어로 메시지를 번역합니다.",
    "qualityTitle": "번역 품질 안내",
    "qualityP1Lead": "번역은 언어 모델에 의해 생성되며 ",
    "qualityP1Bold": "오류가 포함될 수 있습니다",
    "qualityP1Tail": ". 기본 번역 경로가 실패하면 대체 제공자로 전환되며, 그래도 번역할 수 없는 경우 원본 텍스트를 전송합니다. 메시지는 손실되지 않지만 번역되지 않은 상태로 전달될 수 있습니다.",
    "qualityP2": "모든 메시지는 원본을 다시 확인할 수 있습니다. 중요한 내용은 번역에만 의존하지 말고 원본과 대조하십시오. 오역이 심각한 결과를 초래할 수 있는 상황에서는 LinguaFlow를 사용하지 마십시오.",
    "responsibilitiesTitle": "사용자의 책임",
    "responsibilitiesItem1": "불법적이거나 괴롭힘, 타인의 권리를 침해하는 콘텐츠를 전송하지 않습니다.",
    "responsibilitiesItem2Prefix": "민감한 개인정보를 전송하지 않습니다. 메시지 전송 경로는 ",
    "responsibilitiesItem2Link": "개인정보 처리방침",
    "responsibilitiesItem2Suffix": "을 참조하십시오.",
    "responsibilitiesItem3": "로그인 계정 정보를 안전하게 관리하십시오.",
    "accountsTitle": "계정 정책",
    "accountsDesc": "본 환경은 실제 운영 환경이 아닌 학습용 프로젝트이므로, 개발 과정에서 사전 공지 없이 계정이나 데이터가 삭제될 수 있습니다.",
    "backToRegister": "← 회원가입으로 돌아가기"
  },
  "fr": {
    "title": "Conditions d'utilisation",
    "updated": "Applicable à la version MVP pour les cours.",
    "calloutLead": "LinguaFlow est un projet d'étudiants. Le système est fourni ",
    "calloutBold": "en l'état, sans aucune garantie",
    "calloutTail": ", et peut connaître des interruptions ou des pertes de données à tout moment.",
    "serviceTitle": "Ce que fait ce service",
    "serviceDesc": "LinguaFlow traduit les messages d'une conversation dans la langue choisie par chaque destinataire, en utilisant les messages récents comme contexte.",
    "qualityTitle": "Qualité de la traduction",
    "qualityP1Lead": "Les traductions sont générées par des modèles de langage et ",
    "qualityP1Bold": "peuvent contenir des erreurs",
    "qualityP1Tail": ". En cas d'échec du fournisseur principal, le système bascule sur un service de secours, et si la traduction échoue encore, le message original est transmis — aucun message n'est perdu, mais il peut arriver non traduit.",
    "qualityP2": "Vous pouvez toujours consulter le texte original. Pour les informations importantes, comparez avec l'original. N'utilisez pas LinguaFlow pour des situations où une erreur de traduction aurait des conséquences graves.",
    "responsibilitiesTitle": "Vos responsabilités",
    "responsibilitiesItem1": "Ne pas envoyer de contenu illégal, harcelant ou portant atteinte aux droits d'autrui.",
    "responsibilitiesItem2Prefix": "Ne pas envoyer de données personnelles sensibles — consultez la ",
    "responsibilitiesItem2Link": "Politique de confidentialité",
    "responsibilitiesItem2Suffix": " pour savoir où transitent les messages.",
    "responsibilitiesItem3": "Conserver vos identifiants en lieu sûr.",
    "accountsTitle": "Comptes",
    "accountsDesc": "L'équipe de développement peut supprimer des comptes ou des données pendant le développement, y compris sans préavis, car il s'agit d'un environnement d'apprentissage.",
    "backToRegister": "← Retour à l'inscription"
  },
  "de": {
    "title": "Nutzungsbedingungen",
    "updated": "Gilt für die MVP-Version im Rahmen des Kurses.",
    "calloutLead": "LinguaFlow ist ein studentisches Projekt. Das System wird ",
    "calloutBold": "ohne Mängelgewähr und ohne Garantie bereitgestellt",
    "calloutTail": ", und es kann jederzeit zu Ausfällen oder Datenverlusten kommen.",
    "serviceTitle": "Funktionsweise des Dienstes",
    "serviceDesc": "LinguaFlow übersetzt Chatnachrichten in die vom jeweiligen Empfänger gewählte Sprache und bezieht die letzten Nachrichten als Kontext ein.",
    "qualityTitle": "Übersetzungsqualität",
    "qualityP1Lead": "Übersetzungen werden durch Sprachmodelle erstellt und ",
    "qualityP1Bold": "können Fehler enthalten",
    "qualityP1Tail": ". Schlägt der Hauptanbieter fehl, wechselt das System zu einem Ausweichanbieter. Kann auch dort nicht übersetzt werden, wird der Originaltext gesendet — Nachrichten gehen nicht verloren, können aber unübersetzt ankommen.",
    "qualityP2": "Der Originaltext kann bei jeder Nachricht eingesehen werden. Bei wichtigen Inhalten prüfen Sie bitte das Original. Nutzen Sie LinguaFlow nicht für Situationen, in denen Fehlübersetzungen schwerwiegende Folgen haben können.",
    "responsibilitiesTitle": "Ihre Pflichten",
    "responsibilitiesItem1": "Keine rechtswidrigen, belästigenden oder rechteverletzenden Inhalte senden.",
    "responsibilitiesItem2Prefix": "Keine sensiblen persönlichen Informationen senden — siehe ",
    "responsibilitiesItem2Link": "Datenschutzerklärung",
    "responsibilitiesItem2Suffix": ", um den Datenfluss zu verstehen.",
    "responsibilitiesItem3": "Zugangsdaten sicher verwahren.",
    "accountsTitle": "Konten",
    "accountsDesc": "Das Entwicklerteam kann Konten oder Daten während der Entwicklung ohne vorherige Ankündigung löschen, da es sich um eine Lernumgebung handelt.",
    "backToRegister": "← Zurück zur Registrierung"
  },
  "es": {
    "title": "Términos del servicio",
    "updated": "Aplicable a la versión MVP del curso.",
    "calloutLead": "LinguaFlow es un proyecto de curso estudiantil. El sistema se proporciona ",
    "calloutBold": "tal cual, sin garantías de ningún tipo",
    "calloutTail": ", y puede sufrir interrupciones o pérdida de datos en cualquier momento.",
    "serviceTitle": "Qué hace este servicio",
    "serviceDesc": "LinguaFlow traduce los mensajes del chat al idioma elegido por cada destinatario, utilizando los mensajes recientes como contexto.",
    "qualityTitle": "Calidad de traducción",
    "qualityP1Lead": "Las traducciones son generadas por modelos de lenguaje y ",
    "qualityP1Bold": "pueden contener errores",
    "qualityP1Tail": ". Cuando el proveedor principal falla, el sistema pasa a un proveedor de respaldo, y si sigue sin poder traducirse, envía el texto original; los mensajes nunca se pierden, pero pueden llegar sin traducir.",
    "qualityP2": "Siempre es posible ver el texto original de cada mensaje. Para asuntos importantes, verifique con el original. No use LinguaFlow en situaciones donde un error de traducción pueda tener consecuencias graves.",
    "responsibilitiesTitle": "Tus responsabilidades",
    "responsibilitiesItem1": "No enviar contenido ilegal, acosador o que infrinja derechos de terceros.",
    "responsibilitiesItem2Prefix": "No enviar información personal confidencial; consulta la ",
    "responsibilitiesItem2Link": "Política de privacidad",
    "responsibilitiesItem2Suffix": " para saber a dónde viajan los mensajes.",
    "responsibilitiesItem3": "Mantener seguras tus credenciales de acceso.",
    "accountsTitle": "Cuentas",
    "accountsDesc": "El equipo de desarrollo puede eliminar cuentas o datos durante el desarrollo sin previo aviso, ya que se trata de un entorno de aprendizaje.",
    "backToRegister": "← Volver al registro"
  },
  "th": {
    "title": "ข้อกำหนดในการให้บริการ",
    "updated": "ใช้สำหรับเวอร์ชัน MVP ในรายวิชา",
    "calloutLead": "LinguaFlow เป็นโครงงานของนักศึกษา ระบบนี้ให้บริการ",
    "calloutBold": "ตามสภาพโดยไม่มีการรับประกันใดๆ",
    "calloutTail": " และอาจหยุดทำงานหรือสูญหายของข้อมูลได้ตลอดเวลา",
    "serviceTitle": "บริการนี้ทำอะไร",
    "serviceDesc": "LinguaFlow แปลข้อความในการสนทนาเป็นภาษาที่ผู้รับแต่ละคนเลือก โดยอ้างอิงข้อความล่าสุดสองสามข้อความเป็นบริบท",
    "qualityTitle": "เกี่ยวกับคุณภาพการแปล",
    "qualityP1Lead": "คำแปลสร้างขึ้นโดยโมเดลภาษาและ",
    "qualityP1Bold": "อาจมีข้อผิดพลาดได้",
    "qualityP1Tail": " เมื่อเส้นทางการแปลหลักล้มเหลว ระบบจะสลับไปยังผู้ให้บริการสำรอง และหากยังแปลไม่ได้ก็จะส่งข้อความต้นฉบับ — ข้อความจะไม่สูญหายแต่อาจส่งถึงในรูปแบบที่ยังไม่ได้แปล",
    "qualityP2": "คุณสามารถดูข้อความต้นฉบับได้เสมอ สำหรับเรื่องสำคัญโปรดตรวจสอบกับต้นฉบับ อย่าใช้ LinguaFlow ในสถานการณ์ที่การแปลผิดพลาดอาจก่อให้เกิดผลร้ายแรง",
    "responsibilitiesTitle": "ความรับผิดชอบของคุณ",
    "responsibilitiesItem1": "ไม่ส่งเนื้อหาที่ผิดกฎหมาย คุกคาม หรือละเมิดสิทธิ์ของผู้อื่น",
    "responsibilitiesItem2Prefix": "ไม่ส่งข้อมูลส่วนบุคคลที่ละเอียดอ่อน — ดู",
    "responsibilitiesItem2Link": "นโยบายความเป็นส่วนตัว",
    "responsibilitiesItem2Suffix": "เพื่อดูว่าข้อความถูกส่งไปที่ใด",
    "responsibilitiesItem3": "รักษาความปลอดภัยของข้อมูลการเข้าสู่ระบบของคุณ",
    "accountsTitle": "บัญชีผู้ใช้",
    "accountsDesc": "ทีมพัฒนาอาจลบบัญชีหรือข้อมูลในระหว่างการพัฒนาโดยไม่ต้องแจ้งล่วงหน้า เนื่องจากนี่เป็นสภาพแวดล้อมเพื่อการเรียนรู้",
    "backToRegister": "← กลับไปหน้าลงทะเบียน"
  },
  "id": {
    "title": "Ketentuan Layanan",
    "updated": "Berlaku untuk versi MVP tugas kuliah.",
    "calloutLead": "LinguaFlow adalah proyek tugas kuliah mahasiswa. Sistem ini disediakan ",
    "calloutBold": "apa adanya, tanpa jaminan apa pun",
    "calloutTail": ", dan dapat mengalami gangguan atau kehilangan data kapan saja.",
    "serviceTitle": "Apa yang dilakukan layanan ini",
    "serviceDesc": "LinguaFlow menerjemahkan pesan obrolan ke dalam bahasa yang dipilih masing-masing penerima, dengan merujuk beberapa pesan terakhir sebagai konteks.",
    "qualityTitle": "Kualitas terjemahan",
    "qualityP1Lead": "Terjemahan dihasilkan oleh model bahasa dan ",
    "qualityP1Bold": "mungkin mengandung kesalahan",
    "qualityP1Tail": ". Ketika jalur utama gagal, sistem beralih ke penyedia cadangan, dan jika masih belum berhasil, teks asli akan dikirimkan — pesan tidak pernah hilang, namun mungkin tiba dalam bentuk belum diterjemahkan.",
    "qualityP2": "Setiap pesan dapat dilihat kembali teks aslinya. Untuk hal penting, periksa teks asli daripada hanya mengandalkan terjemahan. Jangan gunakan LinguaFlow untuk situasi di mana kesalahan terjemahan dapat berakibat fatal.",
    "responsibilitiesTitle": "Tanggung jawab Anda",
    "responsibilitiesItem1": "Tidak mengirim konten yang melanggar hukum, melecehkan, atau melanggar hak orang lain.",
    "responsibilitiesItem2Prefix": "Tidak mengirim informasi pribadi sensitif — lihat ",
    "responsibilitiesItem2Link": "Kebijakan Privasi",
    "responsibilitiesItem2Suffix": " untuk mengetahui ke mana data pesan dikirim.",
    "responsibilitiesItem3": "Menjaga keamanan kredensial masuk Anda.",
    "accountsTitle": "Akun",
    "accountsDesc": "Tim pengembang dapat menghapus akun atau data selama masa pengembangan tanpa pemberitahuan sebelumnya, karena ini adalah lingkungan pembelajaran.",
    "backToRegister": "← Kembali ke pendaftaran"
  },
  "pt": {
    "title": "Termos de Serviço",
    "updated": "Aplicável à versão MVP acadêmica.",
    "calloutLead": "O LinguaFlow é um projeto de estudantes. O sistema é fornecido ",
    "calloutBold": "no estado em que se encontra, sem garantias",
    "calloutTail": ", e pode apresentar indisponibilidade ou perda de dados a qualquer momento.",
    "serviceTitle": "O que este serviço faz",
    "serviceDesc": "O LinguaFlow traduz mensagens de chat para o idioma escolhido por cada destinatário, usando mensagens recentes como contexto.",
    "qualityTitle": "Qualidade da tradução",
    "qualityP1Lead": "As traduções são geradas por modelos de linguagem e ",
    "qualityP1Bold": "podem conter erros",
    "qualityP1Tail": ". Quando a rota principal falha, o sistema alterna para um provedor reserva e, se ainda não traduzir, envia o texto original — mensagens nunca são perdidas, mas podem chegar sem tradução.",
    "qualityP2": "Você sempre pode ver o texto original de cada mensagem. Para assuntos importantes, compare com o original. Não use o LinguaFlow em situações onde erros de tradução causem consequências graves.",
    "responsibilitiesTitle": "Suas responsabilidades",
    "responsibilitiesItem1": "Não enviar conteúdo ilegal, de assédio ou que viole direitos de terceiros.",
    "responsibilitiesItem2Prefix": "Não enviar dados pessoais sensíveis — consulte a ",
    "responsibilitiesItem2Link": "Política de Privacidade",
    "responsibilitiesItem2Suffix": " para saber para onde os dados são enviados.",
    "responsibilitiesItem3": "Manter suas credenciais de acesso em segurança.",
    "accountsTitle": "Contas",
    "accountsDesc": "A equipe de desenvolvimento pode excluir contas ou dados durante o desenvolvimento sem aviso prévio, pois este é um ambiente de aprendizado.",
    "backToRegister": "← Voltar ao cadastro"
  },
  "ru": {
    "title": "Условия использования",
    "updated": "Применяется к учебной версии MVP.",
    "calloutLead": "LinguaFlow — это студенческий учебный проект. Система предоставляется ",
    "calloutBold": "«как есть», без каких-либо гарантий",
    "calloutTail": ", и в любой момент возможны сбои или потеря данных.",
    "serviceTitle": "Что делает этот сервис",
    "serviceDesc": "LinguaFlow переводит сообщения чата на язык, выбранный каждым получателем, используя последние сообщения в качестве контекста.",
    "qualityTitle": "Качество перевода",
    "qualityP1Lead": "Переводы генерируются языковыми моделями и ",
    "qualityP1Bold": "могут содержать ошибки",
    "qualityP1Tail": ". При сбое основного провайдера система переключается на резервный, а если перевод по-прежнему невозможен, отправляет исходный текст — сообщения не теряются, но могут прийти без перевода.",
    "qualityP2": "Для каждого сообщения можно просмотреть оригинал. По важным вопросам сверяйтесь с оригиналом. Не используйте LinguaFlow в ситуациях, где ошибка перевода может повлечь серьезные последствия.",
    "responsibilitiesTitle": "Ваша ответственность",
    "responsibilitiesItem1": "Не отправлять незаконный, оскорбительный или нарушающий чужие права контент.",
    "responsibilitiesItem2Prefix": "Не отправлять конфиденциальные персональные данные — ознакомьтесь с ",
    "responsibilitiesItem2Link": "Политикой конфиденциальности",
    "responsibilitiesItem2Suffix": ", чтобы узнать, куда направляются сообщения.",
    "responsibilitiesItem3": "Обеспечивать сохранность своих учетных данных.",
    "accountsTitle": "Учетные записи",
    "accountsDesc": "Команда разработчиков может удалять учетные записи или данные в процессе разработки без предварительного уведомления, так как это учебная среда.",
    "backToRegister": "← Вернуться к регистрации"
  },
  "ar": {
    "title": "شروط الخدمة",
    "updated": "تسري على إصدار MVP المخصص للدراسة الأكاديمية.",
    "calloutLead": "LinguaFlow هو مشروع دراسي للطلاب. يتم توفير النظام ",
    "calloutBold": "بحالته الراهنة دون أي ضمانات",
    "calloutTail": "، وقد يتعرض للتوقف أو فقدان البيانات في أي وقت.",
    "serviceTitle": "ما تقدمه هذه الخدمة",
    "serviceDesc": "يقوم LinguaFlow بترجمة رسائل المحادثة إلى اللغة التي اختارها كل مستلم للقراءة، مع استخدام الرسائل الأخيرة كسياق.",
    "qualityTitle": "حول جودة الترجمة",
    "qualityP1Lead": "تُنشأ الترجمات بواسطة نماذج اللغة و",
    "qualityP1Bold": "قد تحتوي على أخطاء",
    "qualityP1Tail": ". عند فشل مسار الترجمة الرئيسي، ينتقل النظام إلى موفر احتياطي، وإذا تعذرت الترجمة، يُرسل النص الأصلي — لا تُفقد الرسائل أبدًا، ولكنها قد تصل دون ترجمة.",
    "qualityP2": "يمكنك دائمًا مراجعة النص الأصلي لكل رسالة. بالنسبة للأمور المهمة، قارن مع الأصل بدلاً من الاعتماد فقط على الترجمة. لا تستخدم LinguaFlow في الحالات التي قد تؤدي فيها الترجمة الخاطئة إلى عواقب وخيمة.",
    "responsibilitiesTitle": "مسؤولياتك",
    "responsibilitiesItem1": "عدم إرسال محتوى غير قانوني أو ينطوي على مضايقة أو انتهاك لحقوق الآخرين.",
    "responsibilitiesItem2Prefix": "عدم إرسال معلومات شخصية حساسة — راجع ",
    "responsibilitiesItem2Link": "سياسة الخصوصية",
    "responsibilitiesItem2Suffix": " لمعرفة وجهة محتوى الرسائل.",
    "responsibilitiesItem3": "الحفاظ على أمان بيانات تسجيل الدخول الخاصة بك.",
    "accountsTitle": "الحسابات",
    "accountsDesc": "يجوز لفريق التطوير حذف الحسابات أو البيانات أثناء مرحلة التطوير دون إشعار مسبق، لأن هذه بيئة تعليمية وليست بيئة تشغيل تجارية.",
    "backToRegister": "→ العودة إلى التسجيل"
  },
  "hi": {
    "title": "सेवा की शर्तें",
    "updated": "पाठ्यक्रम MVP रिलीज़ के लिए लागू।",
    "calloutLead": "LinguaFlow एक छात्र पाठ्यक्रम परियोजना है। यह प्रणाली ",
    "calloutBold": "बिना किसी वारंटी के जैसी है वैसी ही प्रदान की जाती है",
    "calloutTail": ", और किसी भी समय डाउनटाइम या डेटा हानि हो सकती है।",
    "serviceTitle": "यह सेवा क्या करती है",
    "serviceDesc": "LinguaFlow हाल के संदेशों को संदर्भ के रूप में उपयोग करके चैट संदेशों को प्रत्येक प्राप्तकर्ता द्वारा चुनी गई भाषा में अनुवाद करता है।",
    "qualityTitle": "अनुवाद गुणवत्ता के बारे में",
    "qualityP1Lead": "अनुवाद भाषा मॉडल द्वारा उत्पन्न किए जाते हैं और ",
    "qualityP1Bold": "उनमें त्रुटियां हो सकती हैं",
    "qualityP1Tail": "। जब प्राथमिक अनुवाद विफल हो जाता है, तो सिस्टम फ़ॉलबैक प्रदाता पर स्विच करता है, और यदि फिर भी अनुवाद नहीं होता है, तो मूल पाठ भेजा जाता है — संदेश कभी नहीं खोते, लेकिन बिना अनुवाद के आ सकते हैं।",
    "qualityP2": "प्रत्येक संदेश के लिए मूल पाठ देखा जा सकता है। महत्वपूर्ण मामलों के लिए, केवल अनुवाद पर भरोसा करने के बजाय मूल से मिलान करें। LinguaFlow का उपयोग उन स्थितियों के लिए न करें जहां गलत अनुवाद से गंभीर परिणाम हो सकते हैं।",
    "responsibilitiesTitle": "आपकी ज़िम्मेदारियाँ",
    "responsibilitiesItem1": "गैर-कानूनी, परेशान करने वाली या दूसरों के अधिकारों का उल्लंघन करने वाली सामग्री न भेजें।",
    "responsibilitiesItem2Prefix": "संवेदनशील व्यक्तिगत जानकारी न भेजें — संदेश डेटा कहाँ जाता है यह जानने के लिए ",
    "responsibilitiesItem2Link": "गोपनीयता नीति",
    "responsibilitiesItem2Suffix": " देखें।",
    "responsibilitiesItem3": "अपने लॉगिन क्रेडेंशियल सुरक्षित रखें।",
    "accountsTitle": "खाते",
    "accountsDesc": "विकास दल विकास के दौरान बिना किसी पूर्व सूचना के खातों या डेटा को हटा सकता है, क्योंकि यह एक शिक्षण वातावरण है।",
    "backToRegister": "← पंजीकरण पर वापस जाएँ"
  }
};

export const PRIVACY_CONTENT: Record<LanguageCode, LegalPrivacyContent> = {
  "en": {
    "title": "Privacy Policy",
    "updated": "Applicable to the coursework MVP release.",
    "calloutLead": "LinguaFlow is a student coursework project, not a commercial service. ",
    "calloutBold": "Do not send real or sensitive information through this system.",
    "calloutTail": " The development environment uses unencrypted SQLite, and message content is sent to external services as described below.",
    "storedTitle": "Data stored",
    "storedP1": "All conversation content — both original and translated — is stored long-term for your history. The system does not maintain a separate context store: the context given to translation models is only the 3–5 most recent messages in that conversation.",
    "storedP2": "Accounts store email, username, display name, and reading language. Passwords are only stored as hashes, never in plaintext.",
    "accessTitle": "Who can access",
    "accessItems": [
      "Access permissions are checked per conversation and per user.",
      "API keys and secrets reside in environment configuration files, not in source code.",
      "Production deployments enable data encryption at rest. Development environments do not — hence the warning above."
    ],
    "thirdPartyTitle": "Where message content leaves the system",
    "thirdPartyDesc": "Translating a message means sending it to an external service. There are three channels, all configurable:",
    "tableHeaders": [
      "Channel",
      "What is sent",
      "Notes"
    ],
    "tableRows": [
      [
        "LLM Providers (Groq, DeepSeek, Gemini, or OpenAI)",
        "Your message and up to 5 recent messages as context",
        "Subject to the terms of the selected provider"
      ],
      [
        "Fallback Provider (Google Translate via deep-translator)",
        "Full message text",
        {
          "before": "Uses unofficial web endpoint, ",
          "bold": "without a data processing agreement",
          "after": ". Only activated when primary fails."
        }
      ],
      [
        "Langfuse (observability & quality metrics)",
        "Full prompt and result, including message and context",
        "Completely disabled when no API key is configured"
      ]
    ],
    "deletionTitle": "Data deletion",
    "deletionDesc": "Self-service conversation deletion is not available in the MVP version. If you need data removed, please contact the development team.",
    "backToRegister": "← Back to registration"
  },
  "vi": {
    "title": "Chính sách riêng tư",
    "updated": "Áp dụng cho bản MVP dùng trong học phần.",
    "calloutLead": "LinguaFlow là bài tập của môn học, không phải dịch vụ thương mại. ",
    "calloutBold": "Đừng gửi thông tin thật hoặc nhạy cảm qua hệ thống này.",
    "calloutTail": " Môi trường phát triển dùng SQLite không mã hoá, và nội dung tin nhắn được gửi tới các dịch vụ bên ngoài như mô tả bên dưới.",
    "storedTitle": "Dữ liệu được lưu",
    "storedP1": "Toàn bộ nội dung hội thoại — cả bản gốc lẫn bản dịch — được lưu dài hạn để bạn tra cứu lại lịch sử. Hệ thống không giữ một kho ngữ cảnh riêng: phần ngữ cảnh đưa cho mô hình dịch chỉ là kết quả truy vấn 3–5 tin nhắn gần nhất trong chính cuộc trò chuyện đó.",
    "storedP2": "Tài khoản lưu email, tên đăng nhập, tên hiển thị và ngôn ngữ bạn chọn để đọc. Mật khẩu chỉ lưu dưới dạng băm, không bao giờ lưu bản rõ.",
    "accessTitle": "Ai đọc được",
    "accessItems": [
      "Quyền truy cập được kiểm tra theo từng cuộc trò chuyện và từng người dùng.",
      "Khoá API và bí mật nằm trong tệp cấu hình môi trường, không nằm trong mã nguồn.",
      "Bản triển khai thật bật mã hoá dữ liệu khi lưu trữ. Môi trường phát triển thì không — đó là lý do cảnh báo ở đầu trang."
    ],
    "thirdPartyTitle": "Nội dung tin nhắn rời khỏi hệ thống ở đâu",
    "thirdPartyDesc": "Dịch một tin nhắn nghĩa là gửi nó cho một dịch vụ bên ngoài. Có ba kênh, và cả ba đều tắt được bằng cấu hình — nhưng tắt kênh đầu tiên thì không còn dịch được nữa.",
    "tableHeaders": [
      "Kênh",
      "Gửi đi những gì",
      "Ghi chú"
    ],
    "tableRows": [
      [
        "Nhà cung cấp mô hình ngôn ngữ (Groq, DeepSeek, Gemini hoặc OpenAI)",
        "Tin nhắn của bạn và tối đa 5 tin nhắn gần nhất làm ngữ cảnh",
        "Theo điều khoản của nhà cung cấp đang được chọn"
      ],
      [
        "Provider dịch dự phòng (Google Translate qua thư viện deep-translator)",
        "Toàn văn tin nhắn",
        {
          "before": "Dùng endpoint web không chính thức, ",
          "bold": "không có hợp đồng xử lý dữ liệu",
          "after": ". Chỉ kích hoạt khi kênh trên thất bại."
        }
      ],
      [
        "Langfuse (ghi vết để đo chất lượng)",
        "Toàn bộ prompt và kết quả, tức gồm cả tin nhắn lẫn ngữ cảnh",
        "Tắt hoàn toàn khi không cấu hình khoá"
      ]
    ],
    "deletionTitle": "Xoá dữ liệu",
    "deletionDesc": "Tính năng tự xoá hội thoại theo yêu cầu chưa có trong bản MVP. Nếu bạn cần xoá dữ liệu, hãy liên hệ nhóm phát triển.",
    "backToRegister": "← Quay lại đăng ký"
  },
  "zh": {
    "title": "隐私政策",
    "updated": "适用于课程 MVP 版本。",
    "calloutLead": "LinguaFlow 是课程作业项目，非商业服务。",
    "calloutBold": "请勿通过本系统发送真实或敏感信息。",
    "calloutTail": "开发环境使用未加密的 SQLite，消息内容将发送至下述外部服务。",
    "storedTitle": "存储的数据",
    "storedP1": "所有对话内容（包括原文和译文）均作长期存储以供查阅历史。系统不保留独立的上下文库：提供给翻译模型的上下文仅为该对话中最近的 3-5 条消息。",
    "storedP2": "账户存储邮箱、用户名、显示名称和阅读语言。密码仅以哈希形式存储，绝不保存明文。",
    "accessTitle": "谁有权访问",
    "accessItems": [
      "访问权限按对话和用户逐一校验。",
      "API 密钥和机密保存在环境配置文件中，不在源代码中。",
      "实际生产部署开启存储加密。开发环境未加密——这也是页首发出警告的原因。"
    ],
    "thirdPartyTitle": "消息内容传输至何处",
    "thirdPartyDesc": "翻译消息意味着将其发送至外部服务。共有三个通道，均可通过配置停用：",
    "tableHeaders": [
      "通道",
      "发送的内容",
      "说明"
    ],
    "tableRows": [
      [
        "语言模型提供商 (Groq, DeepSeek, Gemini 或 OpenAI)",
        "您的消息以及最多 5 条最近消息作为上下文",
        "遵循所选提供商的条款"
      ],
      [
        "备用翻译提供商 (Google Translate 经 deep-translator)",
        "消息全文",
        {
          "before": "使用非官方网页接口，",
          "bold": "无数据处理协议",
          "after": "。仅在主通道失败时启用。"
        }
      ],
      [
        "Langfuse (用于质量追踪与指标)",
        "完整提示词与结果（包含消息和上下文）",
        "未配置密钥时完全关闭"
      ]
    ],
    "deletionTitle": "数据删除",
    "deletionDesc": "MVP 版本暂不支持自助删除对话。如需删除数据，请联系开发团队。",
    "backToRegister": "← 返回注册"
  },
  "ja": {
    "title": "プライバシーポリシー",
    "updated": "授業用 MVP リリースに適用されます。",
    "calloutLead": "LinguaFlow は学生の授業課題であり、商用サービスではありません。",
    "calloutBold": "本システムを通じて実在の機密情報を送信しないでください。",
    "calloutTail": "開発環境では暗号化されていない SQLite を使用しており、メッセージ内容は以下に示す外部サービスへ送信されます。",
    "storedTitle": "保存されるデータ",
    "storedP1": "すべての会話内容（原文および翻訳文）は履歴参照のために長期保存されます。システムは独立したコンテキスト保管庫を持ちません。翻訳モデルに渡されるコンテキストは、その会話の直近3〜5件のメッセージのみです。",
    "storedP2": "アカウントにはメールアドレス、ユーザー名、表示名、読解言語が保存されます。パスワードはハッシュ化されて保存され、平文では保存されません。",
    "accessTitle": "アクセス権限",
    "accessItems": [
      "アクセス権限は会話ごとおよびユーザーごとに確認されます。",
      "API キーやシークレットは環境設定ファイルに保存され、ソースコードには含まれません。",
      "本番環境ではデータの暗号化が有効になりますが、開発環境では無効です（冒頭の警告理由です）。"
    ],
    "thirdPartyTitle": "メッセージが外部に送信される経路",
    "thirdPartyDesc": "メッセージを翻訳することは外部サービスに送信することを意味します。3つの経路があり、すべて設定で無効化可能です：",
    "tableHeaders": [
      "経路",
      "送信内容",
      "備考"
    ],
    "tableRows": [
      [
        "言語モデル提供者 (Groq, DeepSeek, Gemini, OpenAI)",
        "送信メッセージおよび文脈としての直近最大5件のメッセージ",
        "選択された提供者の利用規約に準拠"
      ],
      [
        "フォールバック提供者 (Google Translate / deep-translator)",
        "メッセージ全文",
        {
          "before": "非公式ウェブエンドポイントを使用、",
          "bold": "データ処理契約なし",
          "after": "。メイン経路失敗時のみ有効。"
        }
      ],
      [
        "Langfuse (品質追跡・メトリクス)",
        "プロンプトおよび結果全体（メッセージと文脈を含む）",
        "API キー未設定時は完全に無効"
      ]
    ],
    "deletionTitle": "データ削除",
    "deletionDesc": "MVP 版ではセルフサービスの会話削除機能は提供されていません。データ削除をご希望の場合は開発チームにご連絡ください。",
    "backToRegister": "← 登録に戻る"
  },
  "ko": {
    "title": "개인정보 처리방침",
    "updated": "수업용 MVP 릴리스에 적용됩니다.",
    "calloutLead": "LinguaFlow는 학생 수업 프로젝트이며 상용 서비스가 아닙니다. ",
    "calloutBold": "본 시스템을 통해 실제 민감한 정보를 전송하지 마십시오.",
    "calloutTail": " 개발 환경은 암호화되지 않은 SQLite를 사용하며, 메시지 내용은 아래 설명된 외부 서비스로 전송됩니다.",
    "storedTitle": "저장되는 데이터",
    "storedP1": "모든 대화 내용(원본 및 번역본)은 대화 기록 조회를 위해 장기 보관됩니다. 시스템은 별도의 문맥 저장소를 유지하지 않으며, 번역 모델에 제공되는 문맥은 해당 대화의 최근 3~5개 메시지뿐입니다.",
    "storedP2": "계정에는 이메일, 사용자 이름, 표시 이름, 읽기 언어가 저장됩니다. 비밀번호는 해시 형태로만 저장되며 평문으로 저장되지 않습니다.",
    "accessTitle": "접근 권한",
    "accessItems": [
      "접근 권한은 대화별 및 사용자별로 엄격히 검증됩니다.",
      "API 키와 보안 비밀은 소스 코드가 아닌 환경 설정 파일에 보관됩니다.",
      "실제 배포 환경에서는 데이터 암호화가 활성화되나 개발 환경에서는 비활성화되어 있습니다."
    ],
    "thirdPartyTitle": "메시지 데이터의 외부 전송 경로",
    "thirdPartyDesc": "메시지를 번역한다는 것은 외부 서비스로 전송함을 의미합니다. 세 가지 채널이 있으며 모두 설정을 통해 비활성화할 수 있습니다:",
    "tableHeaders": [
      "채널",
      "전송 내용",
      "비고"
    ],
    "tableRows": [
      [
        "언어 모델 제공자 (Groq, DeepSeek, Gemini, OpenAI)",
        "작성 메시지 및 문맥용 최근 최대 5개 메시지",
        "선택된 제공자의 약관 준수"
      ],
      [
        "대체 번역 제공자 (Google Translate / deep-translator)",
        "메시지 전체 텍스트",
        {
          "before": "비공식 웹 엔드포인트 사용, ",
          "bold": "데이터 처리 계약 없음",
          "after": ". 기본 채널 실패 시에만 활성화."
        }
      ],
      [
        "Langfuse (품질 추적 및 메트릭)",
        "메시지 및 문맥을 포함한 전체 프롬프트 및 결과",
        "키 미설정 시 완전 비활성화"
      ]
    ],
    "deletionTitle": "데이터 삭제",
    "deletionDesc": "MVP 버전에서는 대화 직접 삭제 기능이 지원되지 않습니다. 데이터 삭제가 필요한 경우 개발팀에 문의하십시오.",
    "backToRegister": "← 회원가입으로 돌아가기"
  },
  "fr": {
    "title": "Politique de confidentialité",
    "updated": "Applicable à la version MVP pour les cours.",
    "calloutLead": "LinguaFlow est un projet de cours, pas un service commercial. ",
    "calloutBold": "N'envoyez pas d'informations réelles ou sensibles.",
    "calloutTail": " L'environnement de développement utilise SQLite non chiffré, et les messages sont envoyés à des tiers comme décrit ci-dessous.",
    "storedTitle": "Données stockées",
    "storedP1": "Tout le contenu des conversations (originaux et traductions) est conservé pour votre historique. Le système ne conserve aucun stockage de contexte séparé : le contexte transmis aux modèles se limite aux 3 à 5 messages les plus récents.",
    "storedP2": "Les comptes stockent l'email, le nom d'utilisateur, le nom d'affichage et la langue de lecture. Les mots de passe sont hachés, jamais en clair.",
    "accessTitle": "Qui peut accéder",
    "accessItems": [
      "Les autorisations sont vérifiées par conversation et par utilisateur.",
      "Les clés API et secrets se trouvent dans les fichiers de configuration d'environnement, pas dans le code.",
      "Les déploiements réels chiffrent les données au repos. Les environnements de développement ne le font pas."
    ],
    "thirdPartyTitle": "Où les messages quittent le système",
    "thirdPartyDesc": "Traduire un message implique de l'envoyer à un service externe. Trois canaux existent, tous désactivables :",
    "tableHeaders": [
      "Canal",
      "Données envoyées",
      "Remarques"
    ],
    "tableRows": [
      [
        "Fournisseurs LLM (Groq, DeepSeek, Gemini, OpenAI)",
        "Votre message et jusqu'à 5 messages récents comme contexte",
        "Selon les conditions du fournisseur sélectionné"
      ],
      [
        "Fournisseur de secours (Google Translate via deep-translator)",
        "Texte intégral du message",
        {
          "before": "Utilise un endpoint non officiel, ",
          "bold": "sans contrat de traitement de données",
          "after": ". Activé uniquement en cas d'échec principal."
        }
      ],
      [
        "Langfuse (observabilité & métriques)",
        "Prompt complet et résultat (message et contexte inclus)",
        "Totalement désactivé sans clé API"
      ]
    ],
    "deletionTitle": "Suppression des données",
    "deletionDesc": "La suppression autonome des conversations n'est pas disponible dans le MVP. Contactez l'équipe de développement si nécessaire.",
    "backToRegister": "← Retour à l'inscription"
  },
  "de": {
    "title": "Datenschutzerklärung",
    "updated": "Gilt für die MVP-Version im Rahmen des Kurses.",
    "calloutLead": "LinguaFlow ist ein Kursprojekt, kein kommerzieller Dienst. ",
    "calloutBold": "Senden Sie keine echten oder sensiblen Informationen über dieses System.",
    "calloutTail": " Die Entwicklungsumgebung nutzt unverschlüsseltes SQLite, und Nachrichten werden wie unten beschrieben an externe Dienste gesendet.",
    "storedTitle": "Gespeicherte Daten",
    "storedP1": "Alle Gesprächsinhalte (Originale und Übersetzungen) werden für Ihren Verlauf dauerhaft gespeichert. Es gibt keinen separaten Kontextspeicher: Der den Übersetzungsmodellen übergebene Kontext umfasst lediglich die 3–5 neuesten Nachrichten.",
    "storedP2": "Konten speichern E-Mail, Benutzername, Anzeigename und Lesesprache. Passwörter werden ausschließlich gehasht gespeichert.",
    "accessTitle": "Wer Zugriff hat",
    "accessItems": [
      "Zugriffsrechte werden pro Gespräch und pro Benutzer geprüft.",
      "API-Schlüssel und Geheimnisse liegen in Umgebungskonfigurationen, nicht im Quellcode.",
      "Produktivinstallationen verschlüsseln Daten bei der Speicherung. Entwicklungsumgebungen nicht — daher die obige Warnung."
    ],
    "thirdPartyTitle": "Wohin Nachrichteninhalte übertragen werden",
    "thirdPartyDesc": "Das Übersetzen einer Nachricht erfordert die Übermittlung an einen externen Dienst. Es gibt drei Kanäle, alle konfigurierbar:",
    "tableHeaders": [
      "Kanal",
      "Was gesendet wird",
      "Hinweise"
    ],
    "tableRows": [
      [
        "LLM-Anbieter (Groq, DeepSeek, Gemini oder OpenAI)",
        "Ihre Nachricht und bis zu 5 vorherige Nachrichten als Kontext",
        "Gemäß den Bedingungen des gewählten Anbieters"
      ],
      [
        "Ausweichanbieter (Google Translate über deep-translator)",
        "Vollständiger Nachrichtentext",
        {
          "before": "Nutzt inoffiziellen Web-Endpunkt, ",
          "bold": "ohne Auftragsverarbeitungsvertrag",
          "after": ". Nur aktiv, wenn Hauptkanal fehlschlägt."
        }
      ],
      [
        "Langfuse (Qualitätsmessung & Telemetrie)",
        "Vollständiger Prompt und Ergebnis (inkl. Nachricht und Kontext)",
        "Vollständig deaktiviert ohne konfigurierten Schlüssel"
      ]
    ],
    "deletionTitle": "Datenlöschung",
    "deletionDesc": "Selbstständiges Löschen von Gesprächen ist im MVP noch nicht verfügbar. Bitte kontaktieren Sie bei Bedarf das Entwicklerteam.",
    "backToRegister": "← Zurück zur Registrierung"
  },
  "es": {
    "title": "Política de privacidad",
    "updated": "Aplicable a la versión MVP del curso.",
    "calloutLead": "LinguaFlow es un proyecto de curso, no un servicio comercial. ",
    "calloutBold": "No envíes información real o confidencial a través de este sistema.",
    "calloutTail": " El entorno de desarrollo utiliza SQLite sin cifrar, y los mensajes se envían a servicios externos como se detalla a continuación.",
    "storedTitle": "Datos almacenados",
    "storedP1": "Todo el contenido de las conversaciones (originales y traducciones) se almacena para tu historial. El sistema no mantiene un almacenamiento de contexto separado: el contexto para los modelos se limita a los 3-5 mensajes más recientes.",
    "storedP2": "Las cuentas guardan correo electrónico, nombre de usuario, nombre visible e idioma de lectura. Las contraseñas se almacenan únicamente como hashes.",
    "accessTitle": "Quién tiene acceso",
    "accessItems": [
      "Los permisos de acceso se verifican por conversación y por usuario.",
      "Las claves API y secretos residen en archivos de configuración, no en el código fuente.",
      "Los despliegues reales cifran los datos en reposo. Los entornos de desarrollo no, de ahí la advertencia."
    ],
    "thirdPartyTitle": "Adónde viaja el contenido de los mensajes",
    "thirdPartyDesc": "Traducir un mensaje implica enviarlo a un servicio externo. Existen tres canales, todos configurables:",
    "tableHeaders": [
      "Canal",
      "Qué se envía",
      "Notas"
    ],
    "tableRows": [
      [
        "Proveedores de LLM (Groq, DeepSeek, Gemini u OpenAI)",
        "Tu mensaje y hasta 5 mensajes recientes como contexto",
        "Sujeto a los términos del proveedor seleccionado"
      ],
      [
        "Proveedor de respaldo (Google Translate vía deep-translator)",
        "Texto completo del mensaje",
        {
          "before": "Usa endpoint web no oficial, ",
          "bold": "sin contrato de procesamiento de datos",
          "after": ". Solo activo si falla el principal."
        }
      ],
      [
        "Langfuse (observabilidad y métricas)",
        "Prompt completo y resultado (incluye mensaje y contexto)",
        "Completamente desactivado si no hay clave configurada"
      ]
    ],
    "deletionTitle": "Eliminación de datos",
    "deletionDesc": "La eliminación autónoma de conversaciones no está disponible en la versión MVP. Si necesitas eliminar datos, contacta al equipo de desarrollo.",
    "backToRegister": "← Volver al registro"
  },
  "th": {
    "title": "นโยบายความเป็นส่วนตัว",
    "updated": "ใช้สำหรับเวอร์ชัน MVP ในรายวิชา",
    "calloutLead": "LinguaFlow เป็นโครงงานในรายวิชา ไม่ใช่บริการเชิงพาณิชย์ ",
    "calloutBold": "โปรดอย่าส่งข้อมูลจริงหรือข้อมูลที่ละเอียดอ่อนผ่านระบบนี้",
    "calloutTail": " สภาพแวดล้อมการพัฒนาใช้ SQLite ที่ไม่ได้เข้ารหัส และข้อความจะถูกส่งไปยังบริการภายนอกตามรายละเอียดด้านล่าง",
    "storedTitle": "ข้อมูลที่ถูกจัดเก็บ",
    "storedP1": "เนื้อหาการสนทนาทั้งหมด (ทั้งต้นฉบับและคำแปล) จะถูกจัดเก็บระยะยาวสำหรับประวัติของคุณ ระบบไม่มีคลังบริบทแยกต่างหาก: บริบทที่ส่งให้โมเดลแปลคือข้อความล่าสุด 3–5 ข้อความในการสนทนานั้นเท่านั้น",
    "storedP2": "บัญชีผู้ใช้จะจัดเก็บอีเมล ชื่อผู้ใช้ ชื่อที่แสดง และภาษาที่เลือกอ่าน รหัสผ่านจะถูกจัดเก็บในรูปแบบแฮชเท่านั้น ไม่มีการบันทึกข้อความธรรมดา",
    "accessTitle": "ใครสามารถเข้าถึงได้",
    "accessItems": [
      "สิทธิ์การเข้าถึงจะได้รับการตรวจสอบตามการสนทนาและตามผู้ใช้",
      "คีย์ API และความลับจะอยู่ในไฟล์การกำหนดค่าสภาพแวดล้อม ไม่ได้อยู่ในซอร์สโค้ด",
      "การปรับใช้จริงจะเปิดใช้งานการเข้ารหัสข้อมูลที่เก็บไว้ สภาพแวดล้อมการพัฒนาไม่ได้เข้ารหัส — จึงมีคำเตือนข้างต้น"
    ],
    "thirdPartyTitle": "เนื้อหาข้อความถูกส่งออกไปนอกระบบที่ใด",
    "thirdPartyDesc": "การแปลข้อความหมายถึงการส่งข้อความไปยังบริการภายนอก มี 3 ช่องทางซึ่งสามารถกำหนดค่าปิดได้ทั้งหมด:",
    "tableHeaders": [
      "ช่องทาง",
      "ข้อมูลที่ส่งไป",
      "หมายเหตุ"
    ],
    "tableRows": [
      [
        "ผู้ให้บริการ LLM (Groq, DeepSeek, Gemini หรือ OpenAI)",
        "ข้อความของคุณและข้อความล่าสุดไม่เกิน 5 ข้อความเป็นบริบท",
        "ตามข้อกำหนดของผู้ให้บริการที่เลือก"
      ],
      [
        "ผู้ให้บริการสำรอง (Google Translate ผ่าน deep-translator)",
        "ข้อความฉบับเต็ม",
        {
          "before": "ใช้ endpoint เว็บที่ไม่เป็นทางการ ",
          "bold": "ไม่มีสัญญาประมวลผลข้อมูล",
          "after": " เปิดใช้งานเมื่อช่องทางหลักล้มเหลวเท่านั้น"
        }
      ],
      [
        "Langfuse (บันทึกการติดตามคุณภาพ)",
        "พรอมต์และผลลัพธ์ทั้งหมด รวมถึงข้อความและบริบท",
        "ปิดใช้งานอย่างสมบูรณ์เมื่อไม่ได้กำหนดค่าคีย์"
      ]
    ],
    "deletionTitle": "การลบข้อมูล",
    "deletionDesc": "ฟีเจอร์ลบการสนทนาด้วยตนเองยังไม่มีในเวอร์ชัน MVP หากคุณต้องการลบข้อมูล โปรดติดต่อทีมพัฒนา",
    "backToRegister": "← กลับไปหน้าลงทะเบียน"
  },
  "id": {
    "title": "Kebijakan Privasi",
    "updated": "Berlaku untuk versi MVP tugas kuliah.",
    "calloutLead": "LinguaFlow adalah proyek tugas kuliah, bukan layanan komersial. ",
    "calloutBold": "Jangan mengirim informasi nyata atau sensitif melalui sistem ini.",
    "calloutTail": " Lingkungan pengembangan menggunakan SQLite tanpa enkripsi, dan isi pesan dikirim ke layanan eksternal sebagaimana dijelaskan di bawah ini.",
    "storedTitle": "Data yang disimpan",
    "storedP1": "Seluruh isi percakapan (baik asli maupun terjemahan) disimpan jangka panjang untuk riwayat Anda. Sistem tidak memiliki penyimpanan konteks terpisah: konteks yang diberikan ke model terjemahan hanya 3–5 pesan terakhir dari percakapan tersebut.",
    "storedP2": "Akun menyimpan email, nama pengguna, nama tampilan, dan bahasa membaca. Kata sandi hanya disimpan dalam bentuk hash.",
    "accessTitle": "Siapa yang dapat mengakses",
    "accessItems": [
      "Izin akses diperiksa per percakapan dan per pengguna.",
      "Kunci API dan rahasia berada di file konfigurasi lingkungan, bukan di kode sumber.",
      "Penerapan produksi mengaktifkan enkripsi data saat istirahat. Lingkungan pengembangan tidak — itulah alasan peringatan di atas."
    ],
    "thirdPartyTitle": "Ke mana konten pesan keluar dari sistem",
    "thirdPartyDesc": "Menerjemahkan pesan berarti mengirimkannya ke layanan eksternal. Ada tiga saluran, semuanya dapat dinonaktifkan melalui konfigurasi:",
    "tableHeaders": [
      "Saluran",
      "Apa yang dikirim",
      "Catatan"
    ],
    "tableRows": [
      [
        "Penyedia LLM (Groq, DeepSeek, Gemini, atau OpenAI)",
        "Pesan Anda dan hingga 5 pesan terakhir sebagai konteks",
        "Tunduk pada ketentuan penyedia yang dipilih"
      ],
      [
        "Penyedia Cadangan (Google Translate via deep-translator)",
        "Teks pesan lengkap",
        {
          "before": "Menggunakan endpoint web tidak resmi, ",
          "bold": "tanpa perjanjian pemrosesan data",
          "after": ". Hanya aktif jika jalur utama gagal."
        }
      ],
      [
        "Langfuse (pelacakan kualitas & metrik)",
        "Prompt dan hasil lengkap, termasuk pesan dan konteks",
        "Dinonaktifkan total saat kunci tidak dikonfigurasi"
      ]
    ],
    "deletionTitle": "Penghapusan data",
    "deletionDesc": "Fitur hapus percakapan mandiri belum tersedia dalam versi MVP. Jika Anda perlu menghapus data, hubungi tim pengembang.",
    "backToRegister": "← Kembali ke pendaftaran"
  },
  "pt": {
    "title": "Política de Privacidade",
    "updated": "Aplicável à versão MVP acadêmica.",
    "calloutLead": "O LinguaFlow é um projeto acadêmico, não um serviço comercial. ",
    "calloutBold": "Não envie informações reais ou confidenciais através deste sistema.",
    "calloutTail": " O ambiente de desenvolvimento utiliza SQLite não criptografado, e as mensagens são enviadas para serviços externos conforme descrito abaixo.",
    "storedTitle": "Dados armazenados",
    "storedP1": "Todo o conteúdo das conversas (originais e traduções) é armazenado para seu histórico. O sistema não mantém um armazenamento de contexto separado: o contexto para os modelos se limita às 3 a 5 mensagens mais recentes.",
    "storedP2": "As contas armazenam e-mail, nome de usuário, nome de exibição e idioma de leitura. As senhas são armazenadas apenas como hash.",
    "accessTitle": "Quem tem acesso",
    "accessItems": [
      "As permissões de acesso são verificadas por conversa e por usuário.",
      "Chaves de API e segredos ficam em arquivos de configuração de ambiente, não no código-fonte.",
      "Implantações em produção ativam criptografia em repouso. Ambientes de desenvolvimento não — daí o aviso acima."
    ],
    "thirdPartyTitle": "Para onde os dados das mensagens são enviados",
    "thirdPartyDesc": "Traduzir uma mensagem significa enviá-la para um serviço externo. Existem três canais, todos configuráveis:",
    "tableHeaders": [
      "Canal",
      "O que é enviado",
      "Notas"
    ],
    "tableRows": [
      [
        "Provedores de LLM (Groq, DeepSeek, Gemini ou OpenAI)",
        "Sua mensagem e até 5 mensagens recentes como contexto",
        "Sujeito aos termos do provedor selecionado"
      ],
      [
        "Provedor Reserva (Google Translate via deep-translator)",
        "Texto integral da mensagem",
        {
          "before": "Usa endpoint web não oficial, ",
          "bold": "sem contrato de processamento de dados",
          "after": ". Ativo apenas se o principal falhar."
        }
      ],
      [
        "Langfuse (observabilidade e métricas)",
        "Prompt e resultado completos (inclui mensagem e contexto)",
        "Totalmente desativado quando nenhuma chave está configurada"
      ]
    ],
    "deletionTitle": "Exclusão de dados",
    "deletionDesc": "A exclusão de conversas pelo próprio usuário não está disponível no MVP. Se precisar remover dados, entre em contato com a equipe de desenvolvimento.",
    "backToRegister": "← Voltar ao cadastro"
  },
  "ru": {
    "title": "Политика конфиденциальности",
    "updated": "Применяется к учебной версии MVP.",
    "calloutLead": "LinguaFlow — это учебный проект, а не коммерческий сервис. ",
    "calloutBold": "Не отправляйте реальную или конфиденциальную информацию через эту систему.",
    "calloutTail": " Среда разработки использует незашифрованную базу SQLite, а сообщения отправляются внешним сервисам, как описано ниже.",
    "storedTitle": "Сохраняемые данные",
    "storedP1": "Все содержимое бесед (оригиналы и переводы) сохраняется для вашей истории. Система не ведет отдельного хранилища контекста: моделям передаются только 3–5 последних сообщений из текущей беседы.",
    "storedP2": "В учетной записи хранятся email, имя пользователя, отображаемое имя и язык чтения. Пароли сохраняются исключительно в виде хэшей.",
    "accessTitle": "Кто имеет доступ",
    "accessItems": [
      "Права доступа проверяются для каждой беседы и каждого пользователя отдельно.",
      "API-ключи и секреты хранятся в файлах конфигурации среды, а не в исходном коде.",
      "В рабочей среде включено шифрование данных при хранении. В среде разработки шифрования нет — отсюда предупреждение в начале страницы."
    ],
    "thirdPartyTitle": "Куда передаются сообщения",
    "thirdPartyDesc": "Перевод сообщения означает отправку во внешний сервис. Существует три канала, все они настраиваются:",
    "tableHeaders": [
      "Канал",
      "Что отправляется",
      "Примечания"
    ],
    "tableRows": [
      [
        "Провайдеры LLM (Groq, DeepSeek, Gemini или OpenAI)",
        "Ваше сообщение и до 5 последних сообщений для контекста",
        "В соответствии с условиями выбранного провайдера"
      ],
      [
        "Резервный провайдер (Google Translate через deep-translator)",
        "Полный текст сообщения",
        {
          "before": "Использует неофициальный веб-эндпоинт, ",
          "bold": "без соглашения об обработке данных",
          "after": ". Включается только при сбое основного канала."
        }
      ],
      [
        "Langfuse (мониторинг качества и метрики)",
        "Полный промпт и ответ (включая сообщение и контекст)",
        "Полностью отключен, если ключ не настроен"
      ]
    ],
    "deletionTitle": "Удаление данных",
    "deletionDesc": "Самостоятельное удаление бесед пока недоступно в версии MVP. Если вам требуется удалить данные, свяжитесь с командой разработчиков.",
    "backToRegister": "← Вернуться к регистрации"
  },
  "ar": {
    "title": "سياسة الخصوصية",
    "updated": "تسري على إصدار MVP المخصص للدراسة الأكاديمية.",
    "calloutLead": "LinguaFlow هو مشروع دراسي وليس خدمة تجارية. ",
    "calloutBold": "لا ترسل معلومات حقيقية أو حساسة عبر هذا النظام.",
    "calloutTail": " تستخدم بيئة التطوير قاعدة بيانات SQLite غير مشفرة، ويتم إرسال محتوى الرسائل إلى خدمات خارجية كما هو موضح أدناه.",
    "storedTitle": "البيانات المخزنة",
    "storedP1": "يتم تخزين جميع محتويات المحادثة (النصوص الأصلية والمترجمة) لفترة طويلة لسجلك. لا يحتفظ النظام بمخزن سياق منفصل: السياق المقدم لنماذج الترجمة يقتصر على آخر 3-5 رسائل في تلك المحادثة.",
    "storedP2": "يخزن الحساب البريد الإلكتروني واسم المستخدم والاسم المعروض ولغة القراءة. تُخزن كلمات المرور كرموز تجزئة فقط ولا تُحفظ أبدًا كنص صريح.",
    "accessTitle": "من يمكنه الوصول",
    "accessItems": [
      "يتم التحقق من أذونات الوصول لكل محادثة ولكل مستخدم بشكل منفصل.",
      "توجد مفاتيح API والأسرار في ملفات تكوين البيئة، وليس في التعليمات البرمجية المصدرية.",
      "تُفعل عمليات النشر الإنتاجية تشفير البيانات المخزنة. لا تفعل بيئات التطوير ذلك — ومن هنا جاء التحذير أعلاه."
    ],
    "thirdPartyTitle": "الخدمات الخارجية التي تستقبل محتوى الرسائل",
    "thirdPartyDesc": "ترجمة الرسالة تعني إرسالها إلى خدمة خارجية. توجد ثلاث قنوات، ويمكن تعطيلها جميعًا عبر الإعدادات:",
    "tableHeaders": [
      "القناة",
      "ما يتم إرساله",
      "ملاحظات"
    ],
    "tableRows": [
      [
        "موفرو نماذج اللغة (Groq, DeepSeek, Gemini, OpenAI)",
        "رسالتك وما يصل إلى 5 رسائل حديثة كسياق",
        "وفقًا لشروط الموفر المحدد"
      ],
      [
        "الموفر الاحتياطي (Google Translate عبر deep-translator)",
        "النص الكامل للرسالة",
        {
          "before": "يستخدم نقطة نهاية ويب غير رسمية، ",
          "bold": "بدون اتفاقية معالجة بيانات",
          "after": ". يتم تفعيله فقط عند فشل القناة الرئيسية."
        }
      ],
      [
        "Langfuse (لتتبع الجودة والقياسات)",
        "المطالبة والنتيجة بالكامل (بما في ذلك الرسالة والسياق)",
        "معطل تمامًا عند عدم تكوين مفتاح API"
      ]
    ],
    "deletionTitle": "حذف البيانات",
    "deletionDesc": "ميزة الحذف الذاتي للمحادثات غير متوفرة في إصدار MVP. إذا كنت بحاجة إلى حذف بياناتك، يرجى الاتصال بفريق التطوير.",
    "backToRegister": "→ العودة إلى التسجيل"
  },
  "hi": {
    "title": "गोपनीयता नीति",
    "updated": "पाठ्यक्रम MVP रिलीज़ के लिए लागू।",
    "calloutLead": "LinguaFlow एक पाठ्यक्रम परियोजना है, व्यावसायिक सेवा नहीं। ",
    "calloutBold": "इस प्रणाली के माध्यम से वास्तविक या संवेदनशील जानकारी न भेजें।",
    "calloutTail": " विकास परिवेश अनएन्क्रिप्टेड SQLite का उपयोग करता है, और संदेश सामग्री नीचे वर्णित अनुसार बाहरी सेवाओं को भेजी जाती है।",
    "storedTitle": "संग्रहीत डेटा",
    "storedP1": "आपके इतिहास के लिए सभी वार्तालाप सामग्री (मूल और अनुवाद दोनों) लंबे समय तक संग्रहीत की जाती है। सिस्टम एक अलग संदर्भ स्टोर नहीं रखता है: अनुवाद मॉडल को दिया गया संदर्भ केवल उस बातचीत के सबसे हाल के 3-5 संदेश हैं।",
    "storedP2": "खाते ईमेल, उपयोगकर्ता नाम, प्रदर्शन नाम और पढ़ने की भाषा संग्रहीत करते हैं। पासवर्ड केवल हैश के रूप में संग्रहीत होते हैं, कभी भी सादे पाठ में नहीं।",
    "accessTitle": "किसकी पहुँच है",
    "accessItems": [
      "पहुँच अनुमतियाँ प्रति वार्तालाप और प्रति उपयोगकर्ता जाँची जाती हैं।",
      "API कुंजियाँ और रहस्य पर्यावरण कॉन्फ़िगरेशन फ़ाइलों में रहते हैं, स्रोत कोड में नहीं।",
      "उत्पादन परिनियोजन बाकी डेटा एन्क्रिप्शन को सक्षम करते हैं। विकास परिवेश ऐसा नहीं करते — इसलिए ऊपर दी गई चेतावनी।"
    ],
    "thirdPartyTitle": "संदेश सामग्री सिस्टम से बाहर कहाँ जाती है",
    "thirdPartyDesc": "संदेश का अनुवाद करने का अर्थ है उसे किसी बाहरी सेवा को भेजना। तीन चैनल हैं, सभी को कॉन्फ़िगरेशन द्वारा बंद किया जा सकता है:",
    "tableHeaders": [
      "चैनल",
      "क्या भेजा जाता है",
      "टिप्पणियाँ"
    ],
    "tableRows": [
      [
        "LLM प्रदाता (Groq, DeepSeek, Gemini, या OpenAI)",
        "आपका संदेश और संदर्भ के रूप में 5 हालिया संदेश तक",
        "चयनित प्रदाता की शर्तों के अधीन"
      ],
      [
        "फ़ॉलबैक प्रदाता (Google Translate via deep-translator)",
        "पूरा संदेश पाठ",
        {
          "before": "अनौपचारिक वेब एंडपॉइंट का उपयोग करता है, ",
          "bold": "डेटा प्रसंस्करण समझौते के बिना",
          "after": "। केवल प्राथमिक विफल होने पर सक्रिय होता है।"
        }
      ],
      [
        "Langfuse (गुणवत्ता ट्रैकिंग और मेट्रिक्स)",
        "संदेश और संदर्भ सहित पूर्ण प्रॉम्प्ट और परिणाम",
        "कोई कुंजी कॉन्फ़िगर न होने पर पूरी तरह से अक्षम"
      ]
    ],
    "deletionTitle": "डेटा हटाना",
    "deletionDesc": "MVP संस्करण में वार्तालाप को स्वयं हटाने की सुविधा उपलब्ध नहीं है। यदि आपको डेटा हटवाना है, तो कृपया विकास दल से संपर्क करें।",
    "backToRegister": "← पंजीकरण पर वापस जाएँ"
  }
};
