"""add timezone to users

The browser's IANA name, stored once so the server has a trusted offset.

Without it a proposal could not carry a real time: "3 giờ chiều thứ Sáu" is a
wall clock, and `normalize_action_time` refuses to take an offset from model
output -- a guessed one books a meeting at the wrong hour and nothing says so.
With nowhere to read a trusted timezone, every extracted time landed in
`missing_fields` and the owner retyped it at approval.

Nullable on purpose. An account that has never opened the web client has no
browser to have reported one, and the approval step still asks; this removes
the common case rather than the fallback.

Hand-written rather than autogenerated, for the reason 68a296abc040 gives:
autogenerate wants to drop unrelated pre-existing drift, and adding a column
must not carry that.

Revision ID: a1c4e77b93de
Revises: 68a296abc040
Create Date: 2026-08-29 21:40:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = 'a1c4e77b93de'
down_revision: Union[str, Sequence[str], None] = '68a296abc040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add the nullable IANA timezone name."""
    op.add_column("users", sa.Column("timezone", sa.String(length=64), nullable=True))


def downgrade() -> None:
    """Drop it. Proposals fall back to asking at approval, as they did before."""
    op.drop_column("users", "timezone")
