"""Add assistant_chunks and assistant_user_memory (ADR-37, ADR-38).

Hand-written rather than autogenerated. Autogenerate does not emit
`CREATE EXTENSION`, it renders `Vector` columns as the opaque type it found
rather than as `pgvector`, and it has no opinion at all about the expression
indexes the lexical half of hybrid retrieval needs — all three would have had to
be added by hand afterwards anyway, and a migration half-generated and
half-edited is the one nobody re-reads.

Revision ID: b7d3f91a4c62
Revises: f2b6d84c05e1
Create Date: 2026-08-28

"""

import pgvector.sqlalchemy
import sqlalchemy as sa

from alembic import op

revision = "b7d3f91a4c62"
down_revision = "f2b6d84c05e1"
branch_labels = None
depends_on = None

# Kept in step with EMBEDDING_DIM in src/database/models.py. Repeated as a
# literal because a migration describes the schema as it was on the day it ran:
# importing the constant would make an old migration change meaning the day the
# application moves to a wider model.
EMBEDDING_DIM = 768


def upgrade() -> None:
    # pgvector is already present from ef06ca79ef49; pg_trgm is new. The lexical
    # half of hybrid retrieval needs it, and a fresh database created after this
    # revision would otherwise fail on the trigram index below rather than on
    # anything that explains itself.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    op.create_table(
        "assistant_chunks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("strategy", sa.String(length=30), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("chunk_text", sa.Text(), nullable=False),
        sa.Column(
            "message_ids", sa.Text(), server_default="[]", nullable=False
        ),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("parent_index", sa.Integer(), nullable=True),
        sa.Column(
            "embedding", pgvector.sqlalchemy.Vector(EMBEDDING_DIM), nullable=True
        ),
        sa.Column(
            "embedding_model", sa.String(length=100), server_default="", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(
            "strategy IN ('message', 'turn_window', 'token_window', "
            "'semantic_split', 'parent_child')",
            name="ck_assistant_chunks_strategy",
        ),
        sa.UniqueConstraint(
            "conversation_id",
            "strategy",
            "chunk_index",
            name="uq_assistant_chunks_conversation_strategy_index",
        ),
    )
    # The cheap filter that rides alongside every vector scan. Retrieval must
    # never reach into another conversation, and must never compare vectors from
    # two embedding models, so all three columns are always in the WHERE clause.
    op.create_index(
        "ix_assistant_chunks_scope",
        "assistant_chunks",
        ["conversation_id", "strategy", "embedding_model"],
        unique=False,
    )
    op.create_index(
        "ix_assistant_chunks_embedding",
        "assistant_chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    # Lexical retrieval, the other half of the hybrid. Two indexes because they
    # fail in opposite directions: full-text finds whole words and misses a
    # misspelling, trigram finds the misspelling and a substring of a term but
    # ranks poorly on ordinary prose. Fusing both with the vector ranking is
    # what lifts recall above what any one of them reaches alone.
    #
    # An expression index rather than a stored `tsvector` column, so nothing is
    # added to the row that docs/CONTRACT.md would have to name. `simple` and
    # not a language configuration: this corpus is Vietnamese, English and
    # Japanese in one thread, and every stemmer would be wrong for two of them.
    op.execute(
        "CREATE INDEX ix_assistant_chunks_lexical ON assistant_chunks "
        "USING gin (to_tsvector('simple', chunk_text))"
    )
    op.execute(
        "CREATE INDEX ix_assistant_chunks_trigram ON assistant_chunks "
        "USING gin (chunk_text gin_trgm_ops)"
    )

    op.create_table(
        "assistant_user_memory",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), server_default="0.5", nullable=False),
        sa.Column("source_message_id", sa.String(length=36), nullable=True),
        sa.Column("superseded_by", sa.String(length=36), nullable=True),
        sa.Column(
            "embedding", pgvector.sqlalchemy.Vector(EMBEDDING_DIM), nullable=True
        ),
        sa.Column(
            "embedding_model", sa.String(length=100), server_default="", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"], ondelete="CASCADE"
        ),
        # Deleting a message must not delete what was learned from it, but must
        # not leave a key pointing at nothing either.
        sa.ForeignKeyConstraint(
            ["source_message_id"], ["messages.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by"], ["assistant_user_memory.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(
            "kind IN ('preference', 'fact', 'relationship', 'recurring')",
            name="ck_assistant_user_memory_kind",
        ),
    )
    op.create_index(
        "ix_assistant_user_memory_owner",
        "assistant_user_memory",
        ["user_id", "superseded_by"],
        unique=False,
    )
    op.create_index(
        "ix_assistant_user_memory_embedding",
        "assistant_user_memory",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )


def downgrade() -> None:
    op.drop_index("ix_assistant_user_memory_embedding", table_name="assistant_user_memory")
    op.drop_index("ix_assistant_user_memory_owner", table_name="assistant_user_memory")
    op.drop_table("assistant_user_memory")

    op.execute("DROP INDEX IF EXISTS ix_assistant_chunks_trigram")
    op.execute("DROP INDEX IF EXISTS ix_assistant_chunks_lexical")
    op.drop_index("ix_assistant_chunks_embedding", table_name="assistant_chunks")
    op.drop_index("ix_assistant_chunks_scope", table_name="assistant_chunks")
    op.drop_table("assistant_chunks")

    # The extensions are left in place. `pg_trgm` may be in use by something
    # added after this revision, and dropping an extension takes its operator
    # classes with it — a downgrade must undo this migration, not the database.
