"""add translation_edits

The table behind F-05's edit box (docs/CONTRACT.md §3.10). Append-only: an
account editing the same translation twice leaves two rows, and the newest one
for that account is the one in effect. No unique constraint, for that reason.

Written by hand rather than autogenerated so the index column order is the one
the read path uses — `(translation_id, editor_id, created_at)` answers "this
reader's newest edit for these translations" without a scan.

Revision ID: b7f2c91d4a08
Revises: fc5bba0e11a9
Create Date: 2026-08-15

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7f2c91d4a08'
down_revision: Union[str, Sequence[str], None] = 'fc5bba0e11a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'translation_edits',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('translation_id', sa.String(length=36), nullable=False),
        sa.Column('editor_id', sa.String(length=36), nullable=False),
        sa.Column('edited_text', sa.Text(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['translation_id'],
            ['translation_results.id'],
            ondelete='CASCADE',
        ),
        # CASCADE, unlike `feedbacks.user_id` which restricts: these rows are
        # private to their author, so an account that goes away takes with it
        # the only text nobody else was ever allowed to read.
        sa.ForeignKeyConstraint(['editor_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'ix_translation_edits_lookup',
        'translation_edits',
        ['translation_id', 'editor_id', 'created_at'],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_translation_edits_lookup', table_name='translation_edits')
    op.drop_table('translation_edits')
