/**
 * Nhãn giao diện, tra theo ngôn ngữ giao diện đang chọn (docs/CONTRACT.md §1.2).
 *
 * Khác hai bảng đã có: `i18n.ts/LABELS` phục vụ cặp nhãn song ngữ của trang
 * đăng nhập, `form-messages.ts` phục vụ câu báo lỗi của biểu mẫu. Bảng này là
 * chữ của chính ứng dụng — tiêu đề, mô tả, nút — và là bảng sẽ lớn dần khi từng
 * màn hình được chuyển sang.
 *
 * Phủ đủ **14 mã** mà `GET /languages` trả về, đúng yêu cầu ở §1.2: đã cho chọn
 * thì phải có nhãn. `uiText` vẫn lùi về `en` cho từng khoá còn thiếu, để thêm
 * một nhãn mới không làm vỡ 13 ngôn ngữ còn lại trong lúc chờ dịch.
 *
 * CHƯA QUA SOÁT BẢN NGỮ. Nhãn sai ở một sản phẩm dịch thuật là lỗi đắt hơn bình
 * thường — ưu tiên soát ja, ko, th, ar, hi.
 */

import type { LanguageCode } from "./constants";

export type UiTextKey =
  | "nav.messages"
  | "nav.settings"
  | "nav.main"
  | "settings.title"
  | "settings.signedOut"
  | "settings.reading.title"
  | "settings.reading.hint"
  | "settings.reading.label"
  | "settings.interface.title"
  | "settings.interface.hint"
  | "settings.interface.label"
  | "settings.saving"
  | "settings.activity.title"
  | "settings.activity.hint"
  | "settings.activity.toggle"
  | "settings.activity.note"
  | "settings.theme.title"
  | "settings.theme.hint"
  | "theme.group"
  | "theme.light"
  | "theme.dark"
  | "theme.system";

type UiTextTable = Partial<Record<LanguageCode, Partial<Record<UiTextKey, string>>>> & {
  en: Record<UiTextKey, string>;
};

export const UI_TEXT: UiTextTable = {
  en: {
    "nav.messages": "Messages",
    "nav.settings": "Settings",
    "nav.main": "Main navigation",
    "settings.title": "Settings",
    "settings.signedOut": "Not signed in",
    "settings.reading.title": "Reading language",
    "settings.reading.hint": "Messages other people send are translated into this language. You can still see the original on any message.",
    "settings.reading.label": "The language you want to read",
    "settings.interface.title": "Interface language",
    "settings.interface.hint": "The language of the app itself — menus, buttons and hints. Changing it takes effect immediately and does not re-translate anything.",
    "settings.interface.label": "The language of the app",
    "settings.saving": "Saving…",
    "settings.activity.title": "Activity status",
    "settings.activity.hint": "Show an online dot next to other people's names.",
    "settings.activity.toggle": "Show activity status",
    "settings.activity.note": "This option applies to this browser only. The server does not broadcast online status yet, so it does not change what other people see about you.",
    "settings.theme.title": "Appearance",
    "settings.theme.hint": "Choose a light background, a dark one, or follow the system.",
    "theme.group": "Choose how the app looks",
    "theme.light": "Light",
    "theme.dark": "Dark",
    "theme.system": "Auto",
  },
  vi: {
    "nav.messages": "Tin nhắn",
    "nav.settings": "Cài đặt",
    "nav.main": "Điều hướng chính",
    "settings.title": "Cài đặt",
    "settings.signedOut": "Chưa đăng nhập",
    "settings.reading.title": "Ngôn ngữ đọc",
    "settings.reading.hint": "Mọi tin nhắn người khác gửi sẽ được dịch sang ngôn ngữ này. Bạn vẫn xem được bản gốc trên từng tin.",
    "settings.reading.label": "Ngôn ngữ bạn muốn đọc",
    "settings.interface.title": "Ngôn ngữ giao diện",
    "settings.interface.hint": "Ngôn ngữ của chính ứng dụng — menu, nút bấm, câu hướng dẫn. Đổi là thấy ngay và không dịch lại gì cả.",
    "settings.interface.label": "Ngôn ngữ của ứng dụng",
    "settings.saving": "Đang lưu…",
    "settings.activity.title": "Trạng thái hoạt động",
    "settings.activity.hint": "Hiện chấm báo đang trực tuyến cạnh tên người khác.",
    "settings.activity.toggle": "Hiển thị trạng thái hoạt động",
    "settings.activity.note": "Tuỳ chọn này chỉ áp dụng cho trình duyệt này. Máy chủ chưa phát đi trạng thái trực tuyến, nên nó không đổi những gì người khác thấy về bạn.",
    "settings.theme.title": "Giao diện",
    "settings.theme.hint": "Chọn nền sáng, nền tối, hoặc theo hệ thống.",
    "theme.group": "Chọn giao diện hiển thị",
    "theme.light": "Sáng",
    "theme.dark": "Tối",
    "theme.system": "Tự động",
  },
  zh: {
    "nav.messages": "消息",
    "nav.settings": "设置",
    "nav.main": "主导航",
    "settings.title": "设置",
    "settings.signedOut": "未登录",
    "settings.reading.title": "阅读语言",
    "settings.reading.hint": "别人发来的消息会被翻译成这种语言。你仍然可以在每条消息上查看原文。",
    "settings.reading.label": "你想阅读的语言",
    "settings.interface.title": "界面语言",
    "settings.interface.hint": "应用本身的语言——菜单、按钮和提示。修改后立即生效，不会重新翻译任何内容。",
    "settings.interface.label": "应用的语言",
    "settings.saving": "正在保存…",
    "settings.activity.title": "活动状态",
    "settings.activity.hint": "在其他人的名字旁边显示在线圆点。",
    "settings.activity.toggle": "显示活动状态",
    "settings.activity.note": "此选项仅适用于当前浏览器。服务器尚未广播在线状态，因此不会改变别人看到的你。",
    "settings.theme.title": "外观",
    "settings.theme.hint": "选择浅色背景、深色背景，或跟随系统。",
    "theme.group": "选择显示外观",
    "theme.light": "浅色",
    "theme.dark": "深色",
    "theme.system": "自动",
  },
  ja: {
    "nav.messages": "メッセージ",
    "nav.settings": "設定",
    "nav.main": "メインナビゲーション",
    "settings.title": "設定",
    "settings.signedOut": "ログインしていません",
    "settings.reading.title": "読む言語",
    "settings.reading.hint": "他の人が送ったメッセージはこの言語に翻訳されます。各メッセージで原文も確認できます。",
    "settings.reading.label": "読みたい言語",
    "settings.interface.title": "表示言語",
    "settings.interface.hint": "アプリ自体の言語です。メニュー、ボタン、説明文に使われます。変更するとすぐに反映され、翻訳はやり直されません。",
    "settings.interface.label": "アプリの言語",
    "settings.saving": "保存中…",
    "settings.activity.title": "アクティブ状態",
    "settings.activity.hint": "他の人の名前の横にオンラインの点を表示します。",
    "settings.activity.toggle": "アクティブ状態を表示する",
    "settings.activity.note": "この設定はこのブラウザだけに適用されます。サーバーはまだオンライン状態を配信していないため、他の人から見えるものは変わりません。",
    "settings.theme.title": "外観",
    "settings.theme.hint": "明るい背景、暗い背景、またはシステムに合わせるかを選びます。",
    "theme.group": "表示の見た目を選ぶ",
    "theme.light": "ライト",
    "theme.dark": "ダーク",
    "theme.system": "自動",
  },
  ko: {
    "nav.messages": "메시지",
    "nav.settings": "설정",
    "nav.main": "주 메뉴",
    "settings.title": "설정",
    "settings.signedOut": "로그인하지 않음",
    "settings.reading.title": "읽는 언어",
    "settings.reading.hint": "다른 사람이 보낸 메시지가 이 언어로 번역됩니다. 각 메시지에서 원문도 볼 수 있습니다.",
    "settings.reading.label": "읽고 싶은 언어",
    "settings.interface.title": "화면 언어",
    "settings.interface.hint": "앱 자체의 언어입니다. 메뉴, 버튼, 안내 문구에 쓰입니다. 바꾸면 바로 적용되며 번역을 다시 하지 않습니다.",
    "settings.interface.label": "앱의 언어",
    "settings.saving": "저장 중…",
    "settings.activity.title": "활동 상태",
    "settings.activity.hint": "다른 사람 이름 옆에 온라인 점을 표시합니다.",
    "settings.activity.toggle": "활동 상태 표시",
    "settings.activity.note": "이 설정은 이 브라우저에만 적용됩니다. 서버가 아직 온라인 상태를 알리지 않으므로 다른 사람에게 보이는 것은 달라지지 않습니다.",
    "settings.theme.title": "화면 모양",
    "settings.theme.hint": "밝은 배경, 어두운 배경, 또는 시스템 설정을 따릅니다.",
    "theme.group": "화면 모양 선택",
    "theme.light": "밝게",
    "theme.dark": "어둡게",
    "theme.system": "자동",
  },
  fr: {
    "nav.messages": "Messages",
    "nav.settings": "Paramètres",
    "nav.main": "Navigation principale",
    "settings.title": "Paramètres",
    "settings.signedOut": "Non connecté",
    "settings.reading.title": "Langue de lecture",
    "settings.reading.hint": "Les messages que les autres envoient sont traduits dans cette langue. Vous pouvez toujours voir l’original sur chaque message.",
    "settings.reading.label": "La langue que vous voulez lire",
    "settings.interface.title": "Langue de l’interface",
    "settings.interface.hint": "La langue de l’application elle-même : menus, boutons et indications. Le changement est immédiat et ne retraduit rien.",
    "settings.interface.label": "La langue de l’application",
    "settings.saving": "Enregistrement…",
    "settings.activity.title": "Statut d’activité",
    "settings.activity.hint": "Afficher un point en ligne à côté du nom des autres.",
    "settings.activity.toggle": "Afficher le statut d’activité",
    "settings.activity.note": "Cette option ne vaut que pour ce navigateur. Le serveur ne diffuse pas encore le statut en ligne, donc cela ne change rien à ce que les autres voient de vous.",
    "settings.theme.title": "Apparence",
    "settings.theme.hint": "Choisissez un fond clair, un fond sombre, ou suivez le système.",
    "theme.group": "Choisir l’apparence",
    "theme.light": "Clair",
    "theme.dark": "Sombre",
    "theme.system": "Auto",
  },
  de: {
    "nav.messages": "Nachrichten",
    "nav.settings": "Einstellungen",
    "nav.main": "Hauptnavigation",
    "settings.title": "Einstellungen",
    "settings.signedOut": "Nicht angemeldet",
    "settings.reading.title": "Lesesprache",
    "settings.reading.hint": "Nachrichten anderer werden in diese Sprache übersetzt. Das Original können Sie bei jeder Nachricht weiterhin sehen.",
    "settings.reading.label": "Die Sprache, in der Sie lesen möchten",
    "settings.interface.title": "Sprache der Oberfläche",
    "settings.interface.hint": "Die Sprache der App selbst — Menüs, Schaltflächen und Hinweise. Die Änderung wirkt sofort und übersetzt nichts neu.",
    "settings.interface.label": "Die Sprache der App",
    "settings.saving": "Wird gespeichert…",
    "settings.activity.title": "Aktivitätsstatus",
    "settings.activity.hint": "Einen Online-Punkt neben den Namen anderer anzeigen.",
    "settings.activity.toggle": "Aktivitätsstatus anzeigen",
    "settings.activity.note": "Diese Option gilt nur für diesen Browser. Der Server sendet den Online-Status noch nicht, daher ändert sich nichts an dem, was andere von Ihnen sehen.",
    "settings.theme.title": "Darstellung",
    "settings.theme.hint": "Wählen Sie einen hellen Hintergrund, einen dunklen, oder folgen Sie dem System.",
    "theme.group": "Darstellung wählen",
    "theme.light": "Hell",
    "theme.dark": "Dunkel",
    "theme.system": "Automatisch",
  },
  es: {
    "nav.messages": "Mensajes",
    "nav.settings": "Ajustes",
    "nav.main": "Navegación principal",
    "settings.title": "Ajustes",
    "settings.signedOut": "Sin iniciar sesión",
    "settings.reading.title": "Idioma de lectura",
    "settings.reading.hint": "Los mensajes que envían los demás se traducen a este idioma. Siempre puedes ver el original en cada mensaje.",
    "settings.reading.label": "El idioma en el que quieres leer",
    "settings.interface.title": "Idioma de la interfaz",
    "settings.interface.hint": "El idioma de la propia aplicación: menús, botones e indicaciones. El cambio es inmediato y no vuelve a traducir nada.",
    "settings.interface.label": "El idioma de la aplicación",
    "settings.saving": "Guardando…",
    "settings.activity.title": "Estado de actividad",
    "settings.activity.hint": "Mostrar un punto de conexión junto al nombre de los demás.",
    "settings.activity.toggle": "Mostrar estado de actividad",
    "settings.activity.note": "Esta opción solo vale para este navegador. El servidor todavía no difunde el estado en línea, así que no cambia lo que los demás ven de ti.",
    "settings.theme.title": "Apariencia",
    "settings.theme.hint": "Elige un fondo claro, uno oscuro, o sigue al sistema.",
    "theme.group": "Elegir la apariencia",
    "theme.light": "Claro",
    "theme.dark": "Oscuro",
    "theme.system": "Automático",
  },
  th: {
    "nav.messages": "ข้อความ",
    "nav.settings": "การตั้งค่า",
    "nav.main": "เมนูหลัก",
    "settings.title": "การตั้งค่า",
    "settings.signedOut": "ยังไม่ได้เข้าสู่ระบบ",
    "settings.reading.title": "ภาษาที่ใช้อ่าน",
    "settings.reading.hint": "ข้อความที่คนอื่นส่งมาจะถูกแปลเป็นภาษานี้ คุณยังดูต้นฉบับได้ในแต่ละข้อความ",
    "settings.reading.label": "ภาษาที่คุณต้องการอ่าน",
    "settings.interface.title": "ภาษาของหน้าจอ",
    "settings.interface.hint": "ภาษาของตัวแอปเอง ทั้งเมนู ปุ่ม และคำแนะนำ เปลี่ยนแล้วเห็นผลทันทีและไม่แปลอะไรใหม่",
    "settings.interface.label": "ภาษาของแอป",
    "settings.saving": "กำลังบันทึก…",
    "settings.activity.title": "สถานะการใช้งาน",
    "settings.activity.hint": "แสดงจุดออนไลน์ข้างชื่อคนอื่น",
    "settings.activity.toggle": "แสดงสถานะการใช้งาน",
    "settings.activity.note": "ตัวเลือกนี้ใช้กับเบราว์เซอร์นี้เท่านั้น เซิร์ฟเวอร์ยังไม่ได้ส่งสถานะออนไลน์ จึงไม่เปลี่ยนสิ่งที่คนอื่นเห็นเกี่ยวกับคุณ",
    "settings.theme.title": "รูปลักษณ์",
    "settings.theme.hint": "เลือกพื้นหลังสว่าง พื้นหลังมืด หรือตามระบบ",
    "theme.group": "เลือกรูปลักษณ์การแสดงผล",
    "theme.light": "สว่าง",
    "theme.dark": "มืด",
    "theme.system": "อัตโนมัติ",
  },
  id: {
    "nav.messages": "Pesan",
    "nav.settings": "Pengaturan",
    "nav.main": "Navigasi utama",
    "settings.title": "Pengaturan",
    "settings.signedOut": "Belum masuk",
    "settings.reading.title": "Bahasa bacaan",
    "settings.reading.hint": "Pesan dari orang lain diterjemahkan ke bahasa ini. Anda tetap bisa melihat teks aslinya di setiap pesan.",
    "settings.reading.label": "Bahasa yang ingin Anda baca",
    "settings.interface.title": "Bahasa antarmuka",
    "settings.interface.hint": "Bahasa aplikasi itu sendiri — menu, tombol, dan petunjuk. Perubahan langsung berlaku dan tidak menerjemahkan ulang apa pun.",
    "settings.interface.label": "Bahasa aplikasi",
    "settings.saving": "Menyimpan…",
    "settings.activity.title": "Status aktivitas",
    "settings.activity.hint": "Tampilkan titik daring di samping nama orang lain.",
    "settings.activity.toggle": "Tampilkan status aktivitas",
    "settings.activity.note": "Pilihan ini hanya berlaku untuk peramban ini. Server belum menyiarkan status daring, jadi ini tidak mengubah apa yang orang lain lihat tentang Anda.",
    "settings.theme.title": "Tampilan",
    "settings.theme.hint": "Pilih latar terang, latar gelap, atau ikuti sistem.",
    "theme.group": "Pilih tampilan",
    "theme.light": "Terang",
    "theme.dark": "Gelap",
    "theme.system": "Otomatis",
  },
  pt: {
    "nav.messages": "Mensagens",
    "nav.settings": "Definições",
    "nav.main": "Navegação principal",
    "settings.title": "Definições",
    "settings.signedOut": "Sessão não iniciada",
    "settings.reading.title": "Idioma de leitura",
    "settings.reading.hint": "As mensagens que os outros enviam são traduzidas para este idioma. Pode continuar a ver o original em cada mensagem.",
    "settings.reading.label": "O idioma em que quer ler",
    "settings.interface.title": "Idioma da interface",
    "settings.interface.hint": "O idioma da própria aplicação — menus, botões e indicações. A alteração é imediata e não volta a traduzir nada.",
    "settings.interface.label": "O idioma da aplicação",
    "settings.saving": "A guardar…",
    "settings.activity.title": "Estado de atividade",
    "settings.activity.hint": "Mostrar um ponto de ligação junto ao nome das outras pessoas.",
    "settings.activity.toggle": "Mostrar estado de atividade",
    "settings.activity.note": "Esta opção aplica-se apenas a este navegador. O servidor ainda não difunde o estado em linha, por isso não muda o que os outros veem sobre si.",
    "settings.theme.title": "Aparência",
    "settings.theme.hint": "Escolha um fundo claro, um escuro, ou siga o sistema.",
    "theme.group": "Escolher o aspeto",
    "theme.light": "Claro",
    "theme.dark": "Escuro",
    "theme.system": "Automático",
  },
  ru: {
    "nav.messages": "Сообщения",
    "nav.settings": "Настройки",
    "nav.main": "Основная навигация",
    "settings.title": "Настройки",
    "settings.signedOut": "Вы не вошли",
    "settings.reading.title": "Язык чтения",
    "settings.reading.hint": "Сообщения других людей переводятся на этот язык. Оригинал по-прежнему можно открыть в каждом сообщении.",
    "settings.reading.label": "Язык, на котором вы хотите читать",
    "settings.interface.title": "Язык интерфейса",
    "settings.interface.hint": "Язык самого приложения — меню, кнопки и подсказки. Изменение вступает в силу сразу и ничего не переводит заново.",
    "settings.interface.label": "Язык приложения",
    "settings.saving": "Сохранение…",
    "settings.activity.title": "Статус активности",
    "settings.activity.hint": "Показывать точку «в сети» рядом с именами других.",
    "settings.activity.toggle": "Показывать статус активности",
    "settings.activity.note": "Эта настройка действует только в этом браузере. Сервер пока не передаёт статус «в сети», поэтому она не меняет то, что видят о вас другие.",
    "settings.theme.title": "Оформление",
    "settings.theme.hint": "Выберите светлый фон, тёмный или как в системе.",
    "theme.group": "Выбрать оформление",
    "theme.light": "Светлое",
    "theme.dark": "Тёмное",
    "theme.system": "Авто",
  },
  ar: {
    "nav.messages": "الرسائل",
    "nav.settings": "الإعدادات",
    "nav.main": "التنقل الرئيسي",
    "settings.title": "الإعدادات",
    "settings.signedOut": "لم تسجّل الدخول",
    "settings.reading.title": "لغة القراءة",
    "settings.reading.hint": "تُترجَم الرسائل التي يرسلها الآخرون إلى هذه اللغة. ويمكنك دائمًا رؤية النص الأصلي في كل رسالة.",
    "settings.reading.label": "اللغة التي تريد القراءة بها",
    "settings.interface.title": "لغة الواجهة",
    "settings.interface.hint": "لغة التطبيق نفسه — القوائم والأزرار والإرشادات. يسري التغيير فورًا ولا يعيد ترجمة أي شيء.",
    "settings.interface.label": "لغة التطبيق",
    "settings.saving": "جارٍ الحفظ…",
    "settings.activity.title": "حالة النشاط",
    "settings.activity.hint": "إظهار نقطة الاتصال بجانب أسماء الآخرين.",
    "settings.activity.toggle": "إظهار حالة النشاط",
    "settings.activity.note": "ينطبق هذا الخيار على هذا المتصفح فقط. لا يبثّ الخادم حالة الاتصال بعد، لذا لا يغيّر ما يراه الآخرون عنك.",
    "settings.theme.title": "المظهر",
    "settings.theme.hint": "اختر خلفية فاتحة أو داكنة، أو اتبع النظام.",
    "theme.group": "اختر شكل العرض",
    "theme.light": "فاتح",
    "theme.dark": "داكن",
    "theme.system": "تلقائي",
  },
  hi: {
    "nav.messages": "संदेश",
    "nav.settings": "सेटिंग्स",
    "nav.main": "मुख्य नेविगेशन",
    "settings.title": "सेटिंग्स",
    "settings.signedOut": "साइन इन नहीं किया",
    "settings.reading.title": "पढ़ने की भाषा",
    "settings.reading.hint": "दूसरों के भेजे संदेश इसी भाषा में अनुवाद होते हैं। हर संदेश पर मूल पाठ आप फिर भी देख सकते हैं।",
    "settings.reading.label": "वह भाषा जिसमें आप पढ़ना चाहते हैं",
    "settings.interface.title": "इंटरफ़ेस की भाषा",
    "settings.interface.hint": "ऐप की अपनी भाषा — मेन्यू, बटन और सुझाव। बदलाव तुरंत लागू होता है और कुछ भी दोबारा अनुवाद नहीं होता।",
    "settings.interface.label": "ऐप की भाषा",
    "settings.saving": "सहेजा जा रहा है…",
    "settings.activity.title": "गतिविधि स्थिति",
    "settings.activity.hint": "दूसरों के नाम के पास ऑनलाइन बिंदु दिखाएँ।",
    "settings.activity.toggle": "गतिविधि स्थिति दिखाएँ",
    "settings.activity.note": "यह विकल्प केवल इसी ब्राउज़र पर लागू होता है। सर्वर अभी ऑनलाइन स्थिति प्रसारित नहीं करता, इसलिए दूसरों को आपके बारे में जो दिखता है वह नहीं बदलता।",
    "settings.theme.title": "रूप-रंग",
    "settings.theme.hint": "हल्की पृष्ठभूमि, गहरी पृष्ठभूमि, या सिस्टम के अनुसार चुनें।",
    "theme.group": "रूप-रंग चुनें",
    "theme.light": "हल्का",
    "theme.dark": "गहरा",
    "theme.system": "स्वतः",
  },
};

/**
 * One label in the interface language, falling back to English per key.
 *
 * Per key rather than per table: adding a new string to a screen leaves the
 * other thirteen languages working, with only that one line in English until
 * it is translated.
 */
export function uiText(lang: LanguageCode, key: UiTextKey): string {
  return UI_TEXT[lang]?.[key] ?? UI_TEXT.en[key];
}
