import type { LanguageCode } from "./types";

type Key = "chats" | "all" | "unread" | "groups" | "search" | "new" | "settings" | "language" | "profile" | "notifications" | "privacy" | "aiTools" | "markRead" | "mute" | "noChats" | "adjustSearch";
const en: Record<Key, string> = { chats: "Chats", all: "All", unread: "Unread", groups: "Groups", search: "Search chats...", new: "new", settings: "Settings", language: "Language & translation", profile: "Profile", notifications: "Notifications", privacy: "Privacy & security", aiTools: "AI tools", markRead: "Mark all as read", mute: "Mute notifications", noChats: "No chats found", adjustSearch: "Try a different search or filter" };
const vi: Record<Key, string> = { chats: "Trò chuyện", all: "Tất cả", unread: "Chưa đọc", groups: "Nhóm", search: "Tìm kiếm cuộc trò chuyện...", new: "mới", settings: "Cài đặt", language: "Ngôn ngữ & Bản dịch", profile: "Hồ sơ", notifications: "Thông báo", privacy: "Quyền riêng tư & Bảo mật", aiTools: "AI & Công cụ thông minh", markRead: "Đánh dấu tất cả đã đọc", mute: "Tắt thông báo", noChats: "Không tìm thấy cuộc trò chuyện", adjustSearch: "Hãy thử thay đổi từ khóa hoặc bộ lọc" };
const labels: Record<LanguageCode, Record<Key, string>> = {
  en, vi,
  ja: { chats:"チャット",all:"すべて",unread:"未読",groups:"グループ",search:"会話を検索...",new:"新着",settings:"設定",language:"言語と翻訳",profile:"プロフィール",notifications:"通知",privacy:"プライバシーとセキュリティ",aiTools:"AIとスマートツール",markRead:"すべて既読にする",mute:"通知をミュート",noChats:"会話が見つかりません",adjustSearch:"検索またはフィルターを変更してください" },
  ko: { chats:"채팅",all:"전체",unread:"읽지 않음",groups:"그룹",search:"대화 검색...",new:"새 항목",settings:"설정",language:"언어 및 번역",profile:"프로필",notifications:"알림",privacy:"개인정보 및 보안",aiTools:"AI 및 스마트 도구",markRead:"모두 읽음으로 표시",mute:"알림 음소거",noChats:"대화를 찾을 수 없음",adjustSearch:"검색 또는 필터를 조정해 보세요" },
  zh: { chats:"聊天",all:"全部",unread:"未读",groups:"群组",search:"搜索对话...",new:"新消息",settings:"设置",language:"语言与翻译",profile:"个人资料",notifications:"通知",privacy:"隐私与安全",aiTools:"AI 与智能工具",markRead:"全部标为已读",mute:"静音通知",noChats:"未找到对话",adjustSearch:"请调整搜索或筛选条件" },
  es: { chats:"Chats",all:"Todos",unread:"No leídos",groups:"Grupos",search:"Buscar conversaciones...",new:"nuevo",settings:"Configuración",language:"Idioma y traducción",profile:"Perfil",notifications:"Notificaciones",privacy:"Privacidad y seguridad",aiTools:"IA y herramientas inteligentes",markRead:"Marcar todo como leído",mute:"Silenciar notificaciones",noChats:"No se encontraron conversaciones",adjustSearch:"Ajusta la búsqueda o el filtro" },
  fr: { chats:"Discussions",all:"Tout",unread:"Non lus",groups:"Groupes",search:"Rechercher des conversations...",new:"nouveau",settings:"Paramètres",language:"Langue et traduction",profile:"Profil",notifications:"Notifications",privacy:"Confidentialité et sécurité",aiTools:"IA et outils intelligents",markRead:"Tout marquer comme lu",mute:"Désactiver les notifications",noChats:"Aucune discussion trouvée",adjustSearch:"Modifiez la recherche ou le filtre" },
  de: { chats:"Chats",all:"Alle",unread:"Ungelesen",groups:"Gruppen",search:"Unterhaltungen suchen...",new:"neu",settings:"Einstellungen",language:"Sprache und Übersetzung",profile:"Profil",notifications:"Benachrichtigungen",privacy:"Datenschutz und Sicherheit",aiTools:"KI und intelligente Tools",markRead:"Alle als gelesen markieren",mute:"Benachrichtigungen stummschalten",noChats:"Keine Unterhaltungen gefunden",adjustSearch:"Suche oder Filter anpassen" },
  th: { chats:"แชต",all:"ทั้งหมด",unread:"ยังไม่อ่าน",groups:"กลุ่ม",search:"ค้นหาการสนทนา...",new:"ใหม่",settings:"การตั้งค่า",language:"ภาษาและการแปล",profile:"โปรไฟล์",notifications:"การแจ้งเตือน",privacy:"ความเป็นส่วนตัวและความปลอดภัย",aiTools:"AI และเครื่องมืออัจฉริยะ",markRead:"ทำเครื่องหมายว่าอ่านแล้วทั้งหมด",mute:"ปิดเสียงการแจ้งเตือน",noChats:"ไม่พบการสนทนา",adjustSearch:"ลองปรับการค้นหาหรือตัวกรอง" },
  id: { chats:"Chat",all:"Semua",unread:"Belum dibaca",groups:"Grup",search:"Cari percakapan...",new:"baru",settings:"Pengaturan",language:"Bahasa & Terjemahan",profile:"Profil",notifications:"Notifikasi",privacy:"Privasi & Keamanan",aiTools:"AI & Alat Pintar",markRead:"Tandai semua sudah dibaca",mute:"Bisukan notifikasi",noChats:"Percakapan tidak ditemukan",adjustSearch:"Coba sesuaikan pencarian atau filter" },
};
export const t = (language: LanguageCode, key: Key) => labels[language][key];

const phrases: Partial<Record<LanguageCode, Record<string, string>>> = {
  en: { Contacts: "Contacts", Groups: "Groups", "Search contacts...": "Search contacts...", "Search study groups...": "Search groups...", "multilingual members": "members", "Auto Live Translation Active": "Live translation is on", "Contact Details": "Contact info", "Group Information": "Group info", "Native Language": "Preferred language", "Global Members": "Members", "Mute Notifications": "Mute notifications", Muted: "Muted", Off: "Off", "Pin Conversation": "Pin chat", Pinned: "Pinned", No: "No", Members: "Members", Member: "Member", "Leave Group": "Leave group", "Block Contact": "Block contact", "My Profile": "Profile", Appearance: "Appearance", "Language & Settings": "Language & translation", "Log out": "Log out", "Logging out…": "Logging out…", Light: "Light", Dark: "Dark", "Last seen recently": "Last seen recently", Online: "Online", "New Conversation": "New chat", "Create a New Group": "Create group", "Suggested Contacts": "Suggested contacts", "Forward message": "Forward message", "No other conversation to forward to.": "No other chats available.", "Start a new chat": "Start a new chat" },
  vi: { Contacts: "Liên hệ", Groups: "Nhóm", "Search contacts...": "Tìm kiếm liên hệ...", "Search study groups...": "Tìm kiếm nhóm...", "multilingual members": "thành viên đa ngôn ngữ", "Auto Live Translation Active": "Đang bật dịch trực tiếp tự động", "Contact Details": "Chi tiết liên hệ", "Group Information": "Thông tin nhóm", "Native Language": "Ngôn ngữ mẹ đẻ", "Global Members": "Thành viên quốc tế", "Mute Notifications": "Tắt thông báo", Muted: "Đã tắt", Off: "Tắt", "Pin Conversation": "Ghim cuộc trò chuyện", Pinned: "Đã ghim", No: "Không", Members: "Thành viên", Member: "Thành viên", "Leave Group": "Rời nhóm", "Block Contact": "Chặn liên hệ", "My Profile": "Hồ sơ của tôi", Appearance: "Giao diện", "Language & Settings": "Ngôn ngữ & Cài đặt", "Log out": "Đăng xuất", "Logging out…": "Đang đăng xuất…", Light: "Sáng", Dark: "Tối", "Last seen recently": "Hoạt động gần đây", Online: "Đang hoạt động", "New Conversation": "Cuộc trò chuyện mới", "Create a New Group": "Tạo nhóm mới", "Suggested Contacts": "Liên hệ đề xuất", "Forward message": "Chuyển tiếp tin nhắn", "No other conversation to forward to.": "Không có cuộc trò chuyện khác để chuyển tiếp.", "Start a new chat": "Bắt đầu cuộc trò chuyện mới" },
  ja: { Contacts: "連絡先", Groups: "グループ", "Contact Details": "連絡先の詳細", "Group Information": "グループ情報", "Native Language": "母国語", "Global Members": "世界のメンバー", "Mute Notifications": "通知をミュート", Muted: "ミュート中", Off: "オフ", "Pin Conversation": "会話を固定", Pinned: "固定済み", No: "いいえ", Members: "メンバー", Member: "メンバー", "Leave Group": "グループを退出", "Block Contact": "連絡先をブロック", "My Profile": "マイプロフィール", Appearance: "外観", "Language & Settings": "言語と設定", "Log out": "ログアウト", "Last seen recently": "最近オンライン", Online: "オンライン", "New Conversation": "新しい会話", "Forward message": "メッセージを転送" },
  ko: { Contacts: "연락처", Groups: "그룹", "Contact Details": "연락처 세부정보", "Group Information": "그룹 정보", "Native Language": "모국어", "Global Members": "글로벌 멤버", "Mute Notifications": "알림 음소거", Muted: "음소거됨", Off: "꺼짐", "Pin Conversation": "대화 고정", Pinned: "고정됨", No: "아니요", Members: "멤버", Member: "멤버", "Leave Group": "그룹 나가기", "Block Contact": "연락처 차단", "My Profile": "내 프로필", Appearance: "화면 모드", "Language & Settings": "언어 및 설정", "Log out": "로그아웃", "Last seen recently": "최근 접속", Online: "온라인", "New Conversation": "새 대화", "Forward message": "메시지 전달" },
  zh: { Contacts: "联系人", Groups: "群组", "Contact Details": "联系人详情", "Group Information": "群组信息", "Native Language": "母语", "Global Members": "全球成员", "Mute Notifications": "静音通知", Muted: "已静音", Off: "关闭", "Pin Conversation": "置顶对话", Pinned: "已置顶", No: "否", Members: "成员", Member: "成员", "Leave Group": "退出群组", "Block Contact": "屏蔽联系人", "My Profile": "我的资料", Appearance: "外观", "Language & Settings": "语言和设置", "Log out": "退出登录", "Last seen recently": "最近上线", Online: "在线", "New Conversation": "新对话", "Forward message": "转发消息" },
  es: { Contacts: "Contactos", Groups: "Grupos", "Contact Details": "Detalles del contacto", "Group Information": "Información del grupo", "Native Language": "Idioma nativo", "Mute Notifications": "Silenciar notificaciones", Muted: "Silenciado", Off: "Desactivado", "Pin Conversation": "Fijar conversación", Pinned: "Fijada", No: "No", Members: "Miembros", Member: "Miembro", "Leave Group": "Salir del grupo", "Block Contact": "Bloquear contacto", "My Profile": "Mi perfil", Appearance: "Apariencia", "Language & Settings": "Idioma y configuración", "Log out": "Cerrar sesión", "Last seen recently": "Visto recientemente", Online: "En línea", "New Conversation": "Nueva conversación", "Forward message": "Reenviar mensaje" },
  fr: { Contacts: "Contacts", Groups: "Groupes", "Contact Details": "Détails du contact", "Group Information": "Informations du groupe", "My Profile": "Mon profil", Appearance: "Apparence", "Language & Settings": "Langue et paramètres", "Log out": "Se déconnecter", "Last seen recently": "Vu récemment", Online: "En ligne", "New Conversation": "Nouvelle discussion", "Forward message": "Transférer le message" },
  de: { Contacts: "Kontakte", Groups: "Gruppen", "Contact Details": "Kontaktdetails", "Group Information": "Gruppeninformationen", "My Profile": "Mein Profil", Appearance: "Darstellung", "Language & Settings": "Sprache und Einstellungen", "Log out": "Abmelden", "Last seen recently": "Kürzlich online", Online: "Online", "New Conversation": "Neue Unterhaltung", "Forward message": "Nachricht weiterleiten" },
  th: { Contacts: "รายชื่อติดต่อ", Groups: "กลุ่ม", "Contact Details": "รายละเอียดผู้ติดต่อ", "Group Information": "ข้อมูลกลุ่ม", "My Profile": "โปรไฟล์ของฉัน", Appearance: "รูปลักษณ์", "Language & Settings": "ภาษาและการตั้งค่า", "Log out": "ออกจากระบบ", "Last seen recently": "ออนไลน์ล่าสุด", Online: "ออนไลน์", "New Conversation": "การสนทนาใหม่", "Forward message": "ส่งต่อข้อความ" },
  id: { Contacts: "Kontak", Groups: "Grup", "Contact Details": "Detail kontak", "Group Information": "Informasi grup", "My Profile": "Profil saya", Appearance: "Tampilan", "Language & Settings": "Bahasa & Pengaturan", "Log out": "Keluar", "Last seen recently": "Terakhir dilihat baru-baru ini", Online: "Online", "New Conversation": "Percakapan baru", "Forward message": "Teruskan pesan" },
};

// Complete every locale for every phrase the UI consumes. Keeping this separate
// from the seed catalog makes coverage auditable while older translations stay intact.
const phraseComplements: Record<Exclude<LanguageCode, 'en' | 'vi'>, Record<string, string>> = {
  ja: { Groups:"グループ", "multilingual members":"多言語メンバー", "Auto Live Translation Active":"自動リアルタイム翻訳が有効", "Create a New Group":"新しいグループを作成", "Suggested Contacts":"おすすめの連絡先", "No other conversation to forward to.":"転送先の会話がありません。", "Start a new chat":"新しいチャットを開始", "Logging out…":"ログアウト中…", Light:"ライト", Dark:"ダーク" },
  ko: { Groups:"그룹", "multilingual members":"다국어 멤버", "Auto Live Translation Active":"자동 실시간 번역 활성화", "Create a New Group":"새 그룹 만들기", "Suggested Contacts":"추천 연락처", "No other conversation to forward to.":"전달할 다른 대화가 없습니다.", "Start a new chat":"새 채팅 시작", "Logging out…":"로그아웃 중…", Light:"라이트", Dark:"다크" },
  zh: { Groups:"群组", "multilingual members":"多语言成员", "Auto Live Translation Active":"自动实时翻译已启用", "Create a New Group":"创建新群组", "Suggested Contacts":"推荐联系人", "No other conversation to forward to.":"没有其他可转发的对话。", "Start a new chat":"开始新聊天", "Logging out…":"正在退出…", Light:"浅色", Dark:"深色" },
  es: { Groups:"Grupos", "multilingual members":"miembros multilingües", "Auto Live Translation Active":"Traducción automática en vivo activa", "Global Members":"Miembros globales", "Create a New Group":"Crear un grupo nuevo", "Suggested Contacts":"Contactos sugeridos", "No other conversation to forward to.":"No hay otra conversación a la que reenviar.", "Start a new chat":"Iniciar un chat nuevo", "Logging out…":"Cerrando sesión…", Light:"Claro", Dark:"Oscuro" },
  fr: { Groups:"Groupes", "multilingual members":"membres multilingues", "Auto Live Translation Active":"Traduction automatique en direct activée", "Native Language":"Langue maternelle", "Global Members":"Membres internationaux", "Mute Notifications":"Désactiver les notifications", Muted:"En sourdine", Off:"Désactivé", "Pin Conversation":"Épingler la discussion", Pinned:"Épinglée", No:"Non", Members:"Membres", Member:"Membre", "Leave Group":"Quitter le groupe", "Block Contact":"Bloquer le contact", "Create a New Group":"Créer un groupe", "Suggested Contacts":"Contacts suggérés", "No other conversation to forward to.":"Aucune autre discussion disponible pour le transfert.", "Start a new chat":"Démarrer une discussion", "Logging out…":"Déconnexion…", Light:"Clair", Dark:"Sombre" },
  de: { Groups:"Gruppen", "multilingual members":"mehrsprachige Mitglieder", "Auto Live Translation Active":"Automatische Live-Übersetzung aktiv", "Native Language":"Muttersprache", "Global Members":"Internationale Mitglieder", "Mute Notifications":"Benachrichtigungen stummschalten", Muted:"Stumm", Off:"Aus", "Pin Conversation":"Unterhaltung anheften", Pinned:"Angeheftet", No:"Nein", Members:"Mitglieder", Member:"Mitglied", "Leave Group":"Gruppe verlassen", "Block Contact":"Kontakt blockieren", "Create a New Group":"Neue Gruppe erstellen", "Suggested Contacts":"Vorgeschlagene Kontakte", "No other conversation to forward to.":"Keine andere Unterhaltung zum Weiterleiten vorhanden.", "Start a new chat":"Neuen Chat starten", "Logging out…":"Abmeldung…", Light:"Hell", Dark:"Dunkel" },
  th: { Groups:"กลุ่ม", "multilingual members":"สมาชิกหลายภาษา", "Auto Live Translation Active":"เปิดใช้การแปลสดอัตโนมัติ", "Native Language":"ภาษาแม่", "Global Members":"สมาชิกทั่วโลก", "Mute Notifications":"ปิดเสียงการแจ้งเตือน", Muted:"ปิดเสียงแล้ว", Off:"ปิด", "Pin Conversation":"ปักหมุดการสนทนา", Pinned:"ปักหมุดแล้ว", No:"ไม่", Members:"สมาชิก", Member:"สมาชิก", "Leave Group":"ออกจากกลุ่ม", "Block Contact":"บล็อกผู้ติดต่อ", "Create a New Group":"สร้างกลุ่มใหม่", "Suggested Contacts":"ผู้ติดต่อที่แนะนำ", "No other conversation to forward to.":"ไม่มีการสนทนาอื่นให้ส่งต่อ", "Start a new chat":"เริ่มแชตใหม่", "Logging out…":"กำลังออกจากระบบ…", Light:"สว่าง", Dark:"มืด" },
  id: { Groups:"Grup", "multilingual members":"anggota multibahasa", "Auto Live Translation Active":"Terjemahan langsung otomatis aktif", "Native Language":"Bahasa ibu", "Global Members":"Anggota global", "Mute Notifications":"Bisukan notifikasi", Muted:"Dibisukan", Off:"Mati", "Pin Conversation":"Sematkan percakapan", Pinned:"Disematkan", No:"Tidak", Members:"Anggota", Member:"Anggota", "Leave Group":"Keluar dari grup", "Block Contact":"Blokir kontak", "Create a New Group":"Buat grup baru", "Suggested Contacts":"Kontak yang disarankan", "No other conversation to forward to.":"Tidak ada percakapan lain untuk diteruskan.", "Start a new chat":"Mulai chat baru", "Logging out…":"Sedang keluar…", Light:"Terang", Dark:"Gelap" },
};
for (const language of Object.keys(phraseComplements) as Array<keyof typeof phraseComplements>) {
  Object.assign(phrases[language]!, phraseComplements[language]);
}

const requiredPhraseKeys = ["Contacts","Groups","multilingual members","Auto Live Translation Active","Contact Details","Group Information","Native Language","Global Members","Mute Notifications","Muted","Off","Pin Conversation","Pinned","No","Members","Member","Leave Group","Block Contact","My Profile","Appearance","Language & Settings","Log out","Logging out…","Light","Dark","Last seen recently","Online","New Conversation","Create a New Group","Suggested Contacts","Forward message","No other conversation to forward to.","Start a new chat"];
for (const language of ['ja','ko','zh','es','fr','de','th','id'] as LanguageCode[]) {
  const missing = requiredPhraseKeys.filter((key) => !phrases[language]?.[key]);
  if (missing.length) throw new Error(`Missing ${language} UI translations: ${missing.join(', ')}`);
}

export const tx = (language: LanguageCode, value: string) => phrases[language]?.[value] || value;

const settingKeys = ["Preferred Language","Interface Language","Messages in other languages will automatically appear in your preferred language.","Controls, menus, and system messages use this language.","Automatic Translation","Translate foreign incoming messages instantly","Show Original by Default","Always show the untranslated text alongside translations","Translation Tone","natural","formal","friendly","Display Name","Bio","Save Profile Changes","Sound Notifications","Play audio chime on incoming messages","Read Receipts","Let contacts see when you read their messages","AI Smart Assistance","Enable quick rewrites, tone polish & auto grammar"];
const settingValues: Record<LanguageCode, string[]> = {
  en: ["Translation language","App language","Messages will be translated into this language.","Menus and system messages will use this language.","Automatic translation","Automatically translate incoming messages","Show original messages","Show original text alongside translations","Translation style","Natural","Formal","Friendly","Display name","Bio","Save changes","Notification sounds","Play a sound for new messages","Read receipts","Let contacts know when you've read their messages","AI writing assistance","Enable rewrites, tone suggestions, and grammar corrections"],
  vi: ["Ngôn ngữ ưu tiên","Ngôn ngữ giao diện","Tin nhắn bằng ngôn ngữ khác sẽ tự động hiển thị bằng ngôn ngữ bạn chọn.","Nút điều khiển, menu và thông báo hệ thống dùng ngôn ngữ này.","Tự động dịch","Dịch ngay tin nhắn đến bằng ngôn ngữ khác","Luôn hiện bản gốc","Luôn hiện nội dung chưa dịch cùng bản dịch","Giọng điệu bản dịch","Tự nhiên","Trang trọng","Thân thiện","Tên hiển thị","Giới thiệu","Lưu thay đổi hồ sơ","Âm thanh thông báo","Phát âm thanh khi có tin nhắn đến","Xác nhận đã đọc","Cho phép liên hệ biết khi bạn đã đọc tin nhắn","Trợ lý AI thông minh","Bật viết lại nhanh, điều chỉnh giọng điệu và tự sửa ngữ pháp"],
  ja: ["優先言語","表示言語","他の言語のメッセージは優先言語で自動表示されます。","操作、メニュー、システムメッセージにこの言語を使用します。","自動翻訳","外国語の受信メッセージをすぐに翻訳","既定で原文を表示","翻訳と一緒に未翻訳の文章を常に表示","翻訳のトーン","自然","フォーマル","親しみやすい","表示名","自己紹介","プロフィールの変更を保存","通知音","受信メッセージの通知音を再生","既読通知","メッセージを読んだことを連絡先に表示","AIスマートアシスタント","クイック書き換え、トーン調整、自動文法修正を有効化"],
  ko: ["선호 언어","인터페이스 언어","다른 언어의 메시지가 선호 언어로 자동 표시됩니다.","컨트롤, 메뉴 및 시스템 메시지에 이 언어를 사용합니다.","자동 번역","외국어 수신 메시지를 즉시 번역","기본적으로 원문 표시","번역과 함께 번역되지 않은 텍스트를 항상 표시","번역 어조","자연스럽게","격식 있게","친근하게","표시 이름","소개","프로필 변경 저장","알림 소리","메시지 수신 시 알림음 재생","읽음 확인","메시지를 읽었는지 연락처에 표시","AI 스마트 지원","빠른 재작성, 어조 다듬기 및 자동 문법 교정 활성화"],
  zh: ["首选语言","界面语言","其他语言的消息将自动以首选语言显示。","控件、菜单和系统消息使用此语言。","自动翻译","即时翻译收到的外语消息","默认显示原文","始终在译文旁显示未翻译文本","翻译语气","自然","正式","友好","显示名称","个人简介","保存资料更改","声音通知","收到消息时播放提示音","已读回执","让联系人知道你已阅读消息","AI 智能助手","启用快速改写、语气润色和自动语法修正"],
  es: ["Idioma preferido","Idioma de la interfaz","Los mensajes en otros idiomas aparecerán automáticamente en tu idioma preferido.","Los controles, menús y mensajes del sistema usan este idioma.","Traducción automática","Traducir al instante los mensajes recibidos en otros idiomas","Mostrar original de forma predeterminada","Mostrar siempre el texto sin traducir junto a las traducciones","Tono de traducción","Natural","Formal","Amable","Nombre para mostrar","Biografía","Guardar cambios del perfil","Notificaciones sonoras","Reproducir un sonido al recibir mensajes","Confirmaciones de lectura","Permitir que los contactos vean cuándo lees sus mensajes","Asistencia inteligente con IA","Activar reescritura rápida, ajuste de tono y gramática automática"],
  fr: ["Langue préférée","Langue de l’interface","Les messages dans d’autres langues apparaîtront automatiquement dans votre langue préférée.","Les commandes, menus et messages système utilisent cette langue.","Traduction automatique","Traduire instantanément les messages reçus en langue étrangère","Afficher l’original par défaut","Toujours afficher le texte non traduit avec les traductions","Ton de traduction","Naturel","Formel","Amical","Nom d’affichage","Biographie","Enregistrer les modifications du profil","Notifications sonores","Émettre un son à la réception d’un message","Confirmations de lecture","Permettre aux contacts de voir quand vous lisez leurs messages","Assistance intelligente par IA","Activer la réécriture rapide, l’ajustement du ton et la grammaire automatique"],
  de: ["Bevorzugte Sprache","Oberflächensprache","Nachrichten in anderen Sprachen werden automatisch in der bevorzugten Sprache angezeigt.","Bedienelemente, Menüs und Systemmeldungen verwenden diese Sprache.","Automatische Übersetzung","Eingehende fremdsprachige Nachrichten sofort übersetzen","Original standardmäßig anzeigen","Unübersetzten Text immer neben der Übersetzung anzeigen","Übersetzungsstil","Natürlich","Formell","Freundlich","Anzeigename","Biografie","Profiländerungen speichern","Tonbenachrichtigungen","Bei eingehenden Nachrichten einen Ton abspielen","Lesebestätigungen","Kontakte sehen lassen, wann Nachrichten gelesen wurden","Intelligente KI-Unterstützung","Schnelles Umschreiben, Tonanpassung und automatische Grammatik aktivieren"],
  th: ["ภาษาที่ต้องการ","ภาษาอินเทอร์เฟซ","ข้อความภาษาอื่นจะแสดงเป็นภาษาที่คุณเลือกโดยอัตโนมัติ","ส่วนควบคุม เมนู และข้อความระบบใช้ภาษานี้","การแปลอัตโนมัติ","แปลข้อความภาษาต่างประเทศที่ได้รับทันที","แสดงต้นฉบับเป็นค่าเริ่มต้น","แสดงข้อความที่ยังไม่ได้แปลพร้อมคำแปลเสมอ","โทนการแปล","เป็นธรรมชาติ","เป็นทางการ","เป็นมิตร","ชื่อที่แสดง","ประวัติย่อ","บันทึกการเปลี่ยนแปลงโปรไฟล์","เสียงแจ้งเตือน","เล่นเสียงเมื่อมีข้อความเข้า","ใบตอบรับการอ่าน","ให้ผู้ติดต่อเห็นเมื่อคุณอ่านข้อความ","ผู้ช่วย AI อัจฉริยะ","เปิดใช้การเขียนใหม่ การปรับโทน และตรวจไวยากรณ์อัตโนมัติ"],
  id: ["Bahasa pilihan","Bahasa antarmuka","Pesan dalam bahasa lain akan otomatis tampil dalam bahasa pilihan Anda.","Kontrol, menu, dan pesan sistem menggunakan bahasa ini.","Terjemahan otomatis","Terjemahkan pesan masuk berbahasa asing secara langsung","Tampilkan teks asli secara default","Selalu tampilkan teks yang belum diterjemahkan bersama terjemahan","Nada terjemahan","Alami","Formal","Ramah","Nama tampilan","Bio","Simpan perubahan profil","Notifikasi suara","Putar bunyi saat pesan masuk","Tanda dibaca","Izinkan kontak melihat saat Anda membaca pesan","Bantuan pintar AI","Aktifkan penulisan ulang cepat, penyempurnaan nada, dan tata bahasa otomatis"],
};
export const settingText = (language: LanguageCode, value: string) => {
  const index = settingKeys.indexOf(value);
  return index < 0 ? value : settingValues[language][index];
};

const interactionKeys = ["Messages are translated in real-time. Speak your native language freely.","Replying to","Document or File","Message","Forwarded","Forward","Translate again","Save message","Delete","Search contacts...","Search study groups...","Search people to add...","Select Group Members","Group Details","Create Group","Group icon","Group Name","Description (Optional)","What is this group for?"];
const interactionValues: Record<LanguageCode, string[]> = {
  en: ["Messages are translated automatically. Write in your preferred language.","Replying to","Document or file","Message","Forwarded","Forward","Translate again","Save message","Delete","Search contacts...","Search groups...","Search people...","Add members","Group details","Create group","Group icon","Group name","Description (optional)","What is this group for?"],
  vi: ["Tin nhắn được dịch theo thời gian thực. Hãy thoải mái dùng ngôn ngữ của bạn.","Đang trả lời","Tài liệu hoặc tệp","Nhắn tin","Đã chuyển tiếp","Chuyển tiếp","Dịch lại","Lưu tin nhắn","Xóa","Tìm kiếm liên hệ...","Tìm kiếm nhóm...","Tìm người để thêm...","Chọn thành viên nhóm","Chi tiết nhóm","Tạo nhóm","Biểu tượng nhóm","Tên nhóm","Mô tả (Không bắt buộc)","Nhóm này dùng để làm gì?"],
  ja: ["メッセージはリアルタイムで翻訳されます。母国語で自由に話してください。","返信先","文書またはファイル","メッセージ","転送済み","転送","再翻訳","メッセージを保存","削除","連絡先を検索...","グループを検索...","追加する人を検索...","グループメンバーを選択","グループの詳細","グループを作成","グループアイコン","グループ名","説明（任意）","このグループの目的は？"],
  ko: ["메시지는 실시간으로 번역됩니다. 모국어로 자유롭게 대화하세요.","답장 대상","문서 또는 파일","메시지","전달됨","전달","다시 번역","메시지 저장","삭제","연락처 검색...","그룹 검색...","추가할 사람 검색...","그룹 멤버 선택","그룹 세부정보","그룹 만들기","그룹 아이콘","그룹 이름","설명(선택 사항)","이 그룹의 목적은 무엇인가요?"],
  zh: ["消息会实时翻译。请放心使用您的母语交流。","回复","文档或文件","消息","已转发","转发","重新翻译","保存消息","删除","搜索联系人...","搜索群组...","搜索要添加的人...","选择群组成员","群组详情","创建群组","群组图标","群组名称","描述（可选）","这个群组用于什么？"],
  es: ["Los mensajes se traducen en tiempo real. Habla libremente en tu idioma nativo.","Respondiendo a","Documento o archivo","Mensaje","Reenviado","Reenviar","Traducir de nuevo","Guardar mensaje","Eliminar","Buscar contactos...","Buscar grupos...","Buscar personas para añadir...","Seleccionar miembros del grupo","Detalles del grupo","Crear grupo","Icono del grupo","Nombre del grupo","Descripción (opcional)","¿Para qué es este grupo?"],
  fr: ["Les messages sont traduits en temps réel. Parlez librement dans votre langue maternelle.","Réponse à","Document ou fichier","Message","Transféré","Transférer","Retraduire","Enregistrer le message","Supprimer","Rechercher des contacts...","Rechercher des groupes...","Rechercher des personnes à ajouter...","Sélectionner les membres","Détails du groupe","Créer le groupe","Icône du groupe","Nom du groupe","Description (facultative)","À quoi sert ce groupe ?"],
  de: ["Nachrichten werden in Echtzeit übersetzt. Schreiben Sie frei in Ihrer Muttersprache.","Antwort an","Dokument oder Datei","Nachricht","Weitergeleitet","Weiterleiten","Erneut übersetzen","Nachricht speichern","Löschen","Kontakte suchen...","Gruppen suchen...","Personen zum Hinzufügen suchen...","Gruppenmitglieder auswählen","Gruppendetails","Gruppe erstellen","Gruppensymbol","Gruppenname","Beschreibung (optional)","Wofür ist diese Gruppe gedacht?"],
  th: ["ข้อความได้รับการแปลแบบเรียลไทม์ ใช้ภาษาแม่ของคุณได้อย่างอิสระ","กำลังตอบกลับ","เอกสารหรือไฟล์","ข้อความ","ส่งต่อแล้ว","ส่งต่อ","แปลอีกครั้ง","บันทึกข้อความ","ลบ","ค้นหาผู้ติดต่อ...","ค้นหากลุ่ม...","ค้นหาคนที่จะเพิ่ม...","เลือกสมาชิกกลุ่ม","รายละเอียดกลุ่ม","สร้างกลุ่ม","ไอคอนกลุ่ม","ชื่อกลุ่ม","คำอธิบาย (ไม่บังคับ)","กลุ่มนี้มีไว้เพื่ออะไร?"],
  id: ["Pesan diterjemahkan secara real-time. Gunakan bahasa ibu Anda dengan bebas.","Membalas","Dokumen atau file","Pesan","Diteruskan","Teruskan","Terjemahkan lagi","Simpan pesan","Hapus","Cari kontak...","Cari grup...","Cari orang untuk ditambahkan...","Pilih anggota grup","Detail grup","Buat grup","Ikon grup","Nama grup","Deskripsi (opsional)","Untuk apa grup ini?"],
};
const interactionExtras: Record<LanguageCode, Record<string, string>> = {
  en: {"Show original":"Show original","Hide original":"Hide original","Show translation":"Show translation","Hide translation":"Hide translation"},
  vi: {"Show original":"Hiện bản gốc","Hide original":"Ẩn bản gốc","Show translation":"Hiện bản dịch","Hide translation":"Ẩn bản dịch"},
  ja: {"Show original":"原文を表示","Hide original":"原文を非表示","Show translation":"翻訳を表示","Hide translation":"翻訳を非表示"},
  ko: {"Show original":"원문 표시","Hide original":"원문 숨기기","Show translation":"번역 표시","Hide translation":"번역 숨기기"},
  zh: {"Show original":"显示原文","Hide original":"隐藏原文","Show translation":"显示译文","Hide translation":"隐藏译文"},
  es: {"Show original":"Mostrar original","Hide original":"Ocultar original","Show translation":"Mostrar traducción","Hide translation":"Ocultar traducción"},
  fr: {"Show original":"Afficher l’original","Hide original":"Masquer l’original","Show translation":"Afficher la traduction","Hide translation":"Masquer la traduction"},
  de: {"Show original":"Original anzeigen","Hide original":"Original ausblenden","Show translation":"Übersetzung anzeigen","Hide translation":"Übersetzung ausblenden"},
  th: {"Show original":"แสดงต้นฉบับ","Hide original":"ซ่อนต้นฉบับ","Show translation":"แสดงคำแปล","Hide translation":"ซ่อนคำแปล"},
  id: {"Show original":"Tampilkan asli","Hide original":"Sembunyikan asli","Show translation":"Tampilkan terjemahan","Hide translation":"Sembunyikan terjemahan"},
};
export const interactionText = (language: LanguageCode, value: string) => {
  const index = interactionKeys.indexOf(value);
  return index < 0 ? (interactionExtras[language][value] || value) : interactionValues[language][index];
};
