import { LanguageOption } from '../types';

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  {
    id: 'vietnamese',
    name: 'Vietnamese',
    nativeName: 'Tiếng Việt',
    flag: '🇻🇳',
    code: 'vi',
    sampleGreeting: 'Xin chào 👋',
  },
  {
    id: 'english',
    name: 'English',
    nativeName: 'English',
    flag: '🇺🇸',
    code: 'en',
    sampleGreeting: 'Hello there! 👋',
  },
  {
    id: 'japanese',
    name: 'Japanese',
    nativeName: '日本語',
    flag: '🇯🇵',
    code: 'ja',
    sampleGreeting: 'こんにちは 👋',
  },
  {
    id: 'korean',
    name: 'Korean',
    nativeName: '한국어',
    flag: '🇰🇷',
    code: 'ko',
    sampleGreeting: '안녕하세요 👋',
  },
  {
    id: 'chinese',
    name: 'Chinese',
    nativeName: '中文 (简体)',
    flag: '🇨🇳',
    code: 'zh',
    sampleGreeting: '你好 👋',
  },
  {
    id: 'spanish',
    name: 'Spanish',
    nativeName: 'Español',
    flag: '🇪🇸',
    code: 'es',
    sampleGreeting: '¡Hola! ¿Cómo estás? 👋',
  },
  {
    id: 'french',
    name: 'French',
    nativeName: 'Français',
    flag: '🇫🇷',
    code: 'fr',
    sampleGreeting: 'Bonjour tout le monde 👋',
  },
  {
    id: 'german',
    name: 'German',
    nativeName: 'Deutsch',
    flag: '🇩🇪',
    code: 'de',
    sampleGreeting: 'Guten Tag! Willkommen 👋',
  },
  {
    id: 'thai',
    name: 'Thai',
    nativeName: 'ไทย',
    flag: '🇹🇭',
    code: 'th',
    sampleGreeting: 'สวัสดีครับ 👋',
  },
  {
    id: 'indonesian',
    name: 'Indonesian',
    nativeName: 'Bahasa Indonesia',
    flag: '🇮🇩',
    code: 'id',
    sampleGreeting: 'Halo, selamat datang! 👋',
  },
];
